const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(Number(n)||0);
let DATA={balance:null,resultados:null,flujo:null},NORMALIZED={balance:null,resultados:null,flujo:null};

/* Normalizador de respaldo: la aplicación sigue funcionando aunque el archivo
   externo normalizador.js no haya cargado. Los períodos son siempre dinámicos. */
if(!window.AuditoriaNormalizador){
  window.AuditoriaNormalizador=(()=>{
    const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
    const number=v=>{if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v??'').trim();if(!s)return null;s=s.replace(/\s/g,'');if(/^[-+]?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else if(/^[-+]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(s))s=s.replace(/,/g,'');else s=s.replace(/,/g,'.');const n=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(n)?n:null};
    const extractYears=v=>{if(v instanceof Date&&!isNaN(v))return[String(v.getFullYear())];if(typeof v==='number'&&v>30000&&v<60000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return isNaN(d)?[]:[String(d.getUTCFullYear())]}return[...(String(v??'').match(/20\d{2}/g)||[])].filter((x,i,a)=>a.indexOf(x)===i)};
    const C={
      balance:{caja_bancos:['caja y bancos','disponible','disponibilidades','efectivo','bancos'],creditos_ventas:['creditos comerciales','creditos por ventas','clientes','cuentas por cobrar','deudores por ventas'],inventarios:['inventario','inventarios','existencias','mercaderias','stock'],anticipos_proveedores:['anticipos a proveedores','anticipos proveedores'],otros_activos_corrientes:['otros activos corrientes'],ppe:['activo fijo','activos fijos','bienes de uso','propiedad planta y equipo'],otros_activos_no_corrientes:['otros activos no corrientes'],proveedores:['deudas comerciales','deudas comerciales - cp','proveedores','cuentas por pagar'],prestamos_cp:['deudas financieras - cp','deudas financieras cp','prestamos bancarios cp','prestamos corrientes'],prestamos_lp:['deudas financieras - lp','deudas financieras lp','prestamos bancarios lp','prestamos largo plazo'],acreedores_varios:['acreedores varios'],capital:['capital','capital social'],reservas:['reserva legal','reservas'],resultados_acumulados:['resultados acumulados','resultados no asignados'],resultado_ejercicio:['resultado del ejercicio','resultado neto del ejercicio'],total_activo_corriente:['total activo corriente'],total_activo_no_corriente:['total activo no corriente'],total_activo:['total activo'],total_pasivo_corriente:['total pasivo corriente'],total_pasivo_no_corriente:['total pasivo no corriente'],total_pasivo:['total pasivo'],total_patrimonio:['total patrimonio neto','total patrimonio','patrimonio neto']},
      resultados:{ventas:['ventas netas','ventas'],costo_ventas:['costo de ventas','costo de mercaderias vendidas'],resultado_bruto:['resultado bruto comercial principal','resultado bruto total','resultado bruto'],gastos_comerciales:['gastos operativos, administrativos y de ventas','gastos de ventas','gastos comerciales'],gastos_administrativos:['gastos administrativos','gastos de administracion'],otros_gastos_operativos:['otros egresos operativos'],ebitda:['ebitda','flujo operativo puro/caja real','flujo operativo puro'],ebit:['ebit','resultado operativo','resultado operativo contable'],intereses_gasto:['intereses financieros pagados','intereses pagados'],intereses_ingreso:['intereses financieros cobrados','intereses ganados'],diferencia_cambio:['perdidas por diferencia de cambio','ganancias por diferencia de cambio','diferencia de cambio'],resultado_antes_impuesto:['resultado antes de impuesto','resultado antes de impuestos'],impuesto_renta:['impuesto a la renta','impuesto a las ganancias'],resultado_neto:['resultado neto total del ejercicio','resultado neto de capitalizaciones','resultado neto']},
      flujo:{flujo_operativo:['flujo de efectivo de actividades operativas','flujo operativo'],cobros_clientes:['cobros a clientes','cobros por ventas'],pagos_proveedores:['pagos a proveedores','pago a proveedores'],flujo_inversion:['flujo de efectivo de actividades de inversion','flujo de inversion'],capex:['capex','adquisicion de propiedad planta y equipo'],flujo_financiamiento:['flujo de efectivo de actividades de financiacion','flujo de financiamiento'],prestamos_recibidos:['prestamos recibidos','obtencion de prestamos'],prestamos_pagados:['prestamos pagados','amortizacion de prestamos'],aportes:['aportes de capital','aportes de socios'],dividendos:['dividendos pagados'],flujo_neto:['aumento neto del efectivo','disminucion neta del efectivo','flujo neto de efectivo'],efectivo_inicial:['efectivo inicial','saldo inicial de efectivo'],efectivo_final:['efectivo final','saldo final de efectivo']}
    };
    const bad=/endeudamiento|periodo medio|rotacion|liquidez|score|ratio|margen|cobertura|indicadores|calificacion/;
    const rowText=r=>r.map(norm).filter(Boolean).join(' ');
    function headers(rows){const h={};rows.slice(0,200).forEach(r=>r.forEach((v,i)=>extractYears(v).forEach(y=>{if(h[y]==null)h[y]=i})));return h}
    function match(s,type){const n=norm(s);let best=null;Object.entries(C[type]||{}).forEach(([key,als])=>als.forEach(a=>{const x=norm(a);if(n===x||n.startsWith(x+' ')||n.includes(' '+x)){const score=n===x?100:Math.min(99,Math.max(40,Math.round(x.length/n.length*100)));if(!best||score>best.score)best={key,alias:a,score}}}));return best}
    function bestSheet(doc){let best=doc.sheets[0],score=-1;doc.sheets.forEach(sh=>{const all=sh.rows.slice(0,200).map(rowText).join(' ');let s=(all.match(/balance general|estado de resultados|activo|pasivo|patrimonio|ventas|inventario|proveedores/gi)||[]).length;if(/analisis|ratio|score|indicadores/.test(norm(sh.name)))s-=20;if(s>score){score=s;best=sh}});return best}
    function label(row,type){let best=null;row.forEach(v=>{const s=String(v??'').trim();if(!s||extractYears(s).length||/^[-+]?\(?[\d.,%\s]+\)?$/.test(s))return;const m=match(s,type);if(m&&(!best||m.score>best.m.score))best={s,m}});return best?best.s:''}
    function normalize(doc,type){const sh=bestSheet(doc),h=headers(sh.rows),periods=Object.keys(h).sort(),matched={},unmapped=[];sh.rows.forEach(r=>{const text=label(r,type),m=match(text,type);if(!text||!m||bad.test(norm(text)))return;const values={};periods.forEach(y=>values[y]=number(r[h[y]]));if(!Object.values(values).some(v=>v!==null))return;if(!matched[m.key])matched[m.key]={label:text,alias:m.alias,score:m.score,values};});return{name:doc.name,sheet:sh.name,periods,matched,unmapped}}
    function normalizeCombined(doc){const sh=bestSheet(doc),h=headers(sh.rows),periods=Object.keys(h).sort(),out={balance:{name:doc.name,sheet:sh.name,periods,matched:{},unmapped:[]},resultados:{name:doc.name,sheet:sh.name,periods,matched:{},unmapped:[]}};let section=null;sh.rows.forEach(r=>{const t=rowText(r);if(/1\.\s*balance general/.test(t)||t==='balance general'){section='balance';return}if(/2\.\s*estado de resultados/.test(t)||t==='estado de resultados'){section='resultados';return}if(!section)return;const text=label(r,section),m=match(text,section);if(!text||!m||bad.test(norm(text)))return;const values={};periods.forEach(y=>values[y]=number(r[h[y]]));if(!Object.values(values).some(v=>v!==null))return;if(!out[section].matched[m.key])out[section].matched[m.key]={label:text,alias:m.alias,score:m.score,values}});return out}
    return{normalize,normalizeCombined,number,norm,C};
  })();
}

function setStatus(id,text){$(id).textContent=text}
async function readFile(file){if(!file)return null;const name=file.name.toLowerCase();if(name.endsWith('.csv'))return{name:file.name,sheets:[{name:'CSV',rows:csvRows(await file.text())}]};if(!window.XLSX)throw new Error('No se pudo cargar el lector Excel.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,cellNF:true,cellText:false,raw:true});return{name:file.name,sheets:wb.SheetNames.map(n=>({name:n,rows:XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:'',raw:true,blankrows:true})}))}}
function csvRows(s){return s.split(/\r?\n/).filter(x=>x.trim()).map(line=>{let a=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if((c===','||c===';')&&!q){a.push(cur);cur=''}else cur+=c}a.push(cur);return a})}
function esc(s){return String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function summaryHtml(type,n){const names={balance:'BALANCE GENERAL',resultados:'ESTADO DE RESULTADOS',flujo:'FLUJO DE EFECTIVO'},entries=Object.entries(n.matched),rows=entries.map(([k,x])=>`<tr><td><b>${esc(k)}</b></td><td>${esc(x.label)}</td><td>${esc(x.alias)}</td><td>${x.score}%</td><td>${n.periods.map(y=>`${y}: ${x.values[y]==null?'—':money(x.values[y])}`).join(' · ')}</td></tr>`).join('');return `<div class="alert ok"><strong>${names[type]}</strong><div>Hoja: <b>${esc(n.sheet)}</b> · Períodos: <b>${n.periods.join(', ')||'No identificados'}</b></div><div>Categorías normalizadas: <b>${entries.length}</b></div></div><table class="table"><thead><tr><th>Categoría</th><th>Cuenta detectada</th><th>Coincidencia</th><th>Confianza</th><th>Valores</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No se encontraron cuentas normalizables.</td></tr>'}</tbody></table>`}
function renderAudit(){if(!window.MotorCoherenciaFinanciera)return;const r=MotorCoherenciaFinanciera.ejecutar(NORMALIZED),a=r.hallazgos||[],counts={crit:a.filter(x=>x.nivel==='crit').length,imp:a.filter(x=>x.nivel==='imp').length,warn:a.filter(x=>x.nivel==='warn').length,info:a.filter(x=>x.nivel==='info').length};const html=a.length?a.map(x=>`<div class="alert ${x.nivel}"><strong>${esc(x.titulo)}</strong><div class="why"><b>Fórmula:</b> ${esc(x.formula||'')}</div><div><b>Valores utilizados:</b><pre>${esc(JSON.stringify(x.valores||{},null,2))}</pre></div><div class="why"><b>Interpretación:</b> ${esc(x.interpretacion||'')}</div></div>`).join(''):`<div class="alert ok"><strong>Sin hallazgos en las pruebas ejecutadas</strong><div>Con la información normalizada disponible no se detectó una ruptura que supere los umbrales actuales.</div></div>`;$('auditoria').innerHTML=`<section class="card"><h2>4. AUDITORÍA Y CORRELACIÓN FINANCIERA</h2><div class="body"><div class="kpis"><div class="kpi">Críticas<b>${counts.crit}</b></div><div class="kpi">Importantes<b>${counts.imp}</b></div><div class="kpi">Para indagar<b>${counts.warn}</b></div><div class="kpi">Informativas<b>${counts.info}</b></div><div class="kpi">Períodos<b>${r.years.length}</b></div></div><div class="evidence"><b>Períodos utilizados:</b> ${r.years.join(', ')||'—'}</div>${html}</div></section>`;$('auditoria').classList.remove('hidden')}
async function process(){try{for(const [id,st] of [['balance','sb'],['resultados','sr'],['flujo','sf']]){const f=$(id).files[0];DATA[id]=await readFile(f);setStatus(st,f?f.name:'Sin archivo')}const combined=DATA.balance&&!DATA.resultados?AuditoriaNormalizador.normalizeCombined(DATA.balance):null;NORMALIZED=combined?{balance:combined.balance,resultados:combined.resultados,flujo:DATA.flujo?AuditoriaNormalizador.normalize(DATA.flujo,'flujo'):null}:{balance:DATA.balance?AuditoriaNormalizador.normalize(DATA.balance,'balance'):null,resultados:DATA.resultados?AuditoriaNormalizador.normalize(DATA.resultados,'resultados'):null,flujo:DATA.flujo?AuditoriaNormalizador.normalize(DATA.flujo,'flujo'):null};const all=Object.values(NORMALIZED).filter(Boolean),periods=[...new Set(all.flatMap(x=>x.periods))].sort();$('periodos').value=periods.join(', ');$('ejercicio').value=periods.at(-1)||'';const archivoUnico=combined?`<div class="alert ok"><strong>ARCHIVO ÚNICO DETECTADO</strong><div>Balance General y Estado de Resultados fueron reconocidos dentro de la misma hoja.</div><div>Hoja: <b>${esc(NORMALIZED.balance.sheet)}</b></div></div>`:'';$('controlBody').innerHTML=archivoUnico+`<p><b>Archivos leídos:</b> ${DATA.balance?1:0}${DATA.resultados?' + Estado de Resultados separado':''}${DATA.flujo?' + Flujo de Efectivo':''}</p>${NORMALIZED.balance?summaryHtml('balance',NORMALIZED.balance):''}${NORMALIZED.resultados?summaryHtml('resultados',NORMALIZED.resultados):''}${NORMALIZED.flujo?summaryHtml('flujo',NORMALIZED.flujo):''}`;$('control').classList.remove('hidden');renderAudit()}catch(e){$('controlBody').innerHTML=`<div class="alert crit"><strong>ERROR DE LECTURA</strong><div>${esc(e.message)}</div></div>`;$('control').classList.remove('hidden')}}
function clearFile(id){const input=$(id);if(!input)return;input.value='';const status={balance:'sb',resultados:'sr',flujo:'sf'}[id];DATA[id]=null;NORMALIZED[id]=null;setStatus(status,'Sin archivo');const all=Object.values(NORMALIZED).filter(Boolean),periods=[...new Set(all.flatMap(x=>x.periods))].sort();$('periodos').value=periods.join(', ');$('ejercicio').value=periods.at(-1)||'';if(!all.length){$('control').classList.add('hidden');$('auditoria').classList.add('hidden');$('controlBody').innerHTML=''}}
document.querySelectorAll('.clear-file').forEach(btn=>btn.addEventListener('click',()=>clearFile(btn.dataset.clear)));
function demo(){$('cliente').value='Caso demostrativo';$('periodos').value='';$('ejercicio').value='';$('controlBody').innerHTML='<div class="alert ok"><strong>CASO DEMOSTRATIVO</strong><div>La interfaz está preparada. No se inventan datos para emitir una auditoría.</div></div>';$('control').classList.remove('hidden')}
$('leer').addEventListener('click',process);$('demo').addEventListener('click',demo);
