const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(Number(n)||0);const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
let DATA={balance:null,resultados:null,flujo:null};
function setStatus(id,text){$(id).textContent=text}
async function readFile(file){if(!file) return null;const name=file.name.toLowerCase();if(name.endsWith('.csv')){const text=await file.text();return {name:file.name,sheets:[{name:'CSV',rows:csvRows(text)}]}}if(!window.XLSX)throw new Error('No se pudo cargar el lector Excel. Abra la aplicación con conexión a Internet.');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:false});return {name:file.name,sheets:wb.SheetNames.map(n=>({name:n,rows:XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:''})}))}}
function csvRows(s){return s.split(/\r?\n/).filter(x=>x.trim()).map(line=>{let a=[],cur='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if((c===','||c===';')&&!q){a.push(cur);cur=''}else cur+=c}a.push(cur);return a})}
function detectPeriod(row){const p=[];row.forEach((v,i)=>{const s=String(v);const m=s.match(/\b(20\d{2})\b/g);if(m&&m.length)p.push({i,years:[...new Set(m)]})});return p}
function summarize(doc){if(!doc)return null;let best=doc.sheets[0],score=-1;for(const sh of doc.sheets){let sc=0;for(const r of sh.rows.slice(0,30)){const line=r.map(norm).join(' ');if(/activo|pasivo|patrimonio|ventas|resultado|flujo|efectivo|proveedores|inventario|costo/.test(line))sc++}if(sc>score){score=sc;best=sh}}const periods=[...new Set(best.rows.flatMap(r=>r.flatMap(v=>String(v).match(/\b20\d{2}\b/g)||[])))].sort();const accounts=[];for(const r of best.rows){const label=String(r[0]??'').trim();if(label&&label.length<100)accounts.push(label)}return {sheet:best.name,periods,accounts:accounts.slice(0,25),rows:best.rows}}
async function process(){const files=[['balance','sb','Balance General'],['resultados','sr','Estado de Resultados'],['flujo','sf','Flujo de Efectivo']];try{for(const [id,st] of files){const f=$(id).files[0];DATA[id]=await readFile(f);setStatus(st,f?f.name:'Sin archivo')}const summaries=Object.entries(DATA).filter(([,v])=>v).map(([k,v])=>({tipo:k,...summarize(v)}));const periods=[...new Set(summaries.flatMap(x=>x.periods))].sort();$('periodos').value=periods.join(', ');$('ejercicio').value=periods.at(-1)||'';$('controlBody').innerHTML=`<p><b>Archivos leídos:</b> ${summaries.length}/3</p>${summaries.map(x=>`<div class="alert ok"><strong>${x.tipo.toUpperCase()} — ${x.name}</strong><div>Hoja seleccionada: <b>${x.sheet}</b></div><div>Períodos detectados: <b>${x.periods.join(', ')||'No identificados'}</b></div><div>Cuentas/textos reconocidos inicialmente: <b>${x.accounts.length}</b></div><details><summary>Ver primeras cuentas reconocidas</summary><div class="note">${x.accounts.map(a=>a.replace(/</g,'&lt;')).join('<br>')}</div></details></div>`).join('')}<div class="note">Este control confirma lectura y estructura. Todavía no se debe interpretar una cuenta hasta completar la normalización.</div>`;$('control').classList.remove('hidden')}catch(e){$('controlBody').innerHTML=`<div class="alert crit"><strong>ERROR DE LECTURA</strong>${e.message}</div>`;$('control').classList.remove('hidden')}}
function demo(){ $('cliente').value='Henrique Blanco';$('ejercicio').value='2025';$('periodos').value='2024, 2025';$('controlBody').innerHTML='<div class="alert ok"><strong>CASO DEMOSTRATIVO CARGADO</strong>Se utilizará el caso patrón para validar el motor.</div>'; $('control').classList.remove('hidden');renderAudit();}
function renderAudit(){const html=`<section class="card"><h2>4. AUDITORÍA — MOTOR EN PREPARACIÓN</h2><div class="body"><div class="kpis"><div class="kpi">Críticas<b>—</b></div><div class="kpi">Importantes<b>—</b></div><div class="kpi">Para indagar<b>—</b></div><div class="kpi">Conciliadas<b>—</b></div></div><div class="alert warn"><strong>NORMALIZACIÓN PENDIENTE</strong>La V0.6 verifica primero qué información fue leída. Las pruebas detalladas de correlación, tendencias y dictamen se ejecutarán sobre los datos normalizados en la siguiente etapa.</div></div></section>`;$('auditoria').innerHTML=html;$('auditoria').classList.remove('hidden')}
$('leer').addEventListener('click',process);$('demo').addEventListener('click',demo);