/* AUDITORIA DE COHERENCIA FINANCIERA - V3
   Presentacion ordenada: INCONSISTENCIAS / CORRELACIONES / TENDENCIAS /
   FAVORABLES / PARA INDAGAR / CONCLUSION.
   Esta capa lee directamente NORMALIZED del proceso de carga.
*/
(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=n=>n==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(Number(n));
  const f1=n=>n==null?'—':Number(n).toFixed(1)+'%';
  const f2=n=>n==null?'—':Number(n).toFixed(2)+'x';
  const pct=(a,b)=>a!=null&&b!=null&&b!==0?(a/b-1)*100:null;
  const getNormalized=()=>{try{return(typeof NORMALIZED!=='undefined'?NORMALIZED:null)||window.NORMALIZED||{}}catch(_){return window.NORMALIZED||{}}};
  const val=(d,k,y)=>d?.matched?.[k]?.values?.[y]??null;
  const add=(arr,titulo,lectura,razon,evidencia,periodo)=>arr.push({titulo,lectura,razon,evidencia,periodo});

  function analizar(){
    const n=getNormalized(),b=n.balance,r=n.resultados,f=n.flujo;
    const years=[...new Set([...(b?.periods||[]),...(r?.periods||[]),...(f?.periods||[])].map(String).filter(x=>/^\d{4}$/.test(x)))].sort();
    const data={crit:[],imp:[],warn:[],ok:[],corr:[],trend:[]};
    const all=y=>({ac:val(b,'total_activo',y),pa:val(b,'total_pasivo',y),pn:val(b,'total_patrimonio',y),acorr:val(b,'total_activo_corriente',y),pcorr:val(b,'total_pasivo_corriente',y),inv:val(b,'inventarios',y),cli:val(b,'creditos_ventas',y),prov:val(b,'proveedores',y),ventas:val(r,'ventas',y),costo:val(r,'costo_ventas',y),bruto:val(r,'resultado_bruto',y),ebitda:val(r,'ebitda',y),ebit:val(r,'ebit',y),interes:val(r,'intereses_gasto',y),neto:val(r,'resultado_neto',y)});

    years.forEach(y=>{
      const d=all(y);
      if([d.ac,d.pa,d.pn].every(v=>v!=null)&&!(d.ac===0&&d.pa===0&&d.pn===0)){const dif=d.ac-d.pa-d.pn;if(Math.abs(dif)>1)add(data.crit,'Ecuacion patrimonial no conciliada',`El Balance de ${y} no cierra matematicamente.`,`Debe verificarse la carga, clasificacion o totalizacion de las cuentas antes de utilizar este periodo para conclusiones.`,`Activo ${money(d.ac)} − Pasivo ${money(d.pa)} − Patrimonio ${money(d.pn)} = ${money(dif)}.`,y);else add(data.ok,'Ecuacion patrimonial conciliada',`El Balance de ${y} presenta cierre matematico.`,`Esto valida la aritmetica basica, pero no demuestra por si solo la razonabilidad de las cuentas.`,`Activo ${money(d.ac)} − Pasivo ${money(d.pa)} − Patrimonio ${money(d.pn)} = 0.`,y)}
      if(d.ventas!=null&&d.costo!=null&&d.bruto!=null){const esperado=d.ventas-d.costo,dif=d.bruto-esperado;if(Math.abs(dif)>1)add(data.crit,'Resultado bruto no concilia',`El resultado bruto informado de ${y} no coincide con Ventas − Costo de Ventas.`,`Debe revisarse la clasificacion o carga de los componentes del resultado bruto.`,`Informado ${money(d.bruto)}; esperado ${money(esperado)}; diferencia ${money(dif)}.`,y)}
      if(d.acorr!=null&&d.pcorr!=null&&d.pcorr!==0){const lc=d.acorr/d.pcorr;if(lc<1)add(data.crit,'Liquidez corriente insuficiente',`La cobertura de corto plazo de ${y} es inferior a 1,00x.`,`El activo corriente no alcanza para cubrir el pasivo corriente.`,`Activo corriente ${money(d.acorr)} / Pasivo corriente ${money(d.pcorr)} = ${f2(lc)}.`,y);else if(lc<1.2)add(data.warn,'Liquidez corriente ajustada',`Existe cobertura en ${y}, pero con margen reducido.`,`Una demora de cobranza o menor realizacion de activos puede presionar la capacidad de pago.`,`Liquidez corriente = ${f2(lc)}.`,y);else if(lc>=1.5&&d.inv!=null&&d.inv/d.acorr>=0.60)add(data.warn,'Liquidez concentrada en inventarios',`La liquidez contable de ${y} depende fuertemente de realizar inventarios.`,`No debe confundirse liquidez contable con liquidez inmediata.`,`Inventarios ${money(d.inv)} = ${f1(d.inv/d.acorr*100)} del activo corriente; liquidez ${f2(lc)}.`,y);else add(data.ok,'Cobertura corriente suficiente',`La cobertura corriente de ${y} supera 1,00x.`,`Existe cobertura contable de las obligaciones corrientes.`,`Activo corriente ${money(d.acorr)} / Pasivo corriente ${money(d.pcorr)} = ${f2(lc)}.`,y)}
      if(d.ac!=null&&d.pa!=null&&d.ac!==0){const ende=d.pa/d.ac*100;if(ende>=70)add(data.imp,'Dependencia elevada de terceros',`El pasivo representa ${f1(ende)} del activo en ${y}.`,`La estructura aumenta la sensibilidad ante caida de ventas, menor cobranza o mayores costos financieros.`,`Pasivo ${money(d.pa)} / Activo ${money(d.ac)} = ${f1(ende)}.`,y);else if(ende<=40)add(data.ok,'Estructura patrimonial favorable',`La participacion del pasivo es relativamente baja en ${y}.`,`Es una condicion favorable de estructura, pero no constituye por si sola una conclusion integral de riesgo.`,`Pasivo ${money(d.pa)} / Activo ${money(d.ac)} = ${f1(ende)}.`,y);else add(data.warn,'Estructura patrimonial intermedia',`La dependencia de terceros es moderada en ${y}.`,`Debe analizarse junto con liquidez y generacion operativa.`,`Pasivo ${money(d.pa)} / Activo ${money(d.ac)} = ${f1(ende)}.`,y)}
      if(d.ventas!=null&&d.ventas!==0){if(d.bruto!=null){const m=d.bruto/d.ventas*100;if(m<0)add(data.crit,'Margen bruto negativo',`El costo de ventas supera las ventas en ${y}.`,`La actividad comercial no cubre su costo directo.`,`Ventas ${money(d.ventas)}; Resultado bruto ${money(d.bruto)}; margen ${f1(m)}.`,y);else add(data.ok,'Margen bruto positivo',`La actividad comercial conserva margen bruto en ${y}.`,`Existe resultado despues del costo de ventas; debe analizarse si alcanza para gastos y financiamiento.`,`Ventas ${money(d.ventas)}; Resultado bruto ${money(d.bruto)}; margen ${f1(m)}.`,y)}if(d.ebitda!=null&&d.ebitda<0)add(data.crit,'EBITDA negativo',`La operacion de ${y} no genera resultado antes de depreciaciones y amortizaciones.`,`La generacion operativa informada es insuficiente para sostener la estructura operativa.`,`EBITDA ${money(d.ebitda)}; margen EBITDA ${f1(d.ebitda/d.ventas*100)}.`,y);if(d.neto!=null&&d.neto<0)add(data.imp,'Resultado neto negativo',`El ejercicio ${y} termina con perdida.`,`Debe identificarse que componente explica la perdida y si es recurrente.`,`Ventas ${money(d.ventas)}; Resultado neto ${money(d.neto)}; margen neto ${f1(d.neto/d.ventas*100)}.`,y)}
      if(d.ebitda!=null&&d.ebit!=null&&d.ebitda<d.ebit)add(data.crit,'Relacion EBITDA / EBIT requiere revision',`En ${y}, EBITDA es inferior a EBIT.`,`Debe revisarse la clasificacion de depreciaciones/amortizaciones o la forma de calculo.`,`EBITDA ${money(d.ebitda)} < EBIT ${money(d.ebit)}.`,y);
      if(d.ebitda!=null&&d.interes!=null&&d.interes>0){const cov=d.ebitda/d.interes;if(cov<1)add(data.crit,'Cobertura de intereses insuficiente',`La generacion operativa de ${y} no cubre los intereses financieros.`,`Existe presion financiera que debe contrastarse con caja, deuda y refinanciacion.`,`EBITDA ${money(d.ebitda)} / Intereses ${money(d.interes)} = ${f2(cov)}.`,y);else if(cov<3)add(data.warn,'Cobertura de intereses ajustada',`Los intereses de ${y} estan cubiertos, pero con margen limitado.`,`Una baja adicional de la generacion operativa podria comprometer la cobertura.`,`EBITDA ${money(d.ebitda)} / Intereses ${money(d.interes)} = ${f2(cov)}.`,y);else add(data.ok,'Cobertura de intereses adecuada',`La generacion operativa cubre los intereses de ${y} con margen razonable.`,`La relacion operativa-financiera es favorable en este periodo.`,`EBITDA ${money(d.ebitda)} / Intereses ${money(d.interes)} = ${f2(cov)}.`,y)}
    });

    for(let i=1;i<years.length;i++){
      const p=years[i-1],y=years[i],a=all(p),d=all(y);const vv=pct(d.ventas,a.ventas),vi=pct(d.inv,a.inv),vc=pct(d.cli,a.cli),vp=pct(d.prov,a.prov),va=pct(d.ac,a.ac),vpa=pct(d.pa,a.pa),vpat=pct(d.pn,a.pn);
      if(vv!=null&&vi!=null){const gap=vi-vv;if(gap>25)add(data.corr,'Inventarios crecen mas que las ventas',`Entre ${p} y ${y}, el stock crece mucho mas que la actividad comercial.`,`Puede aumentar el capital inmovilizado y el riesgo de realizacion.`,`Ventas ${f1(vv)}; Inventarios ${f1(vi)}; brecha ${f1(gap)} puntos.`,y);else if(gap<-25)add(data.corr,'Inventarios caen mas que las ventas',`Entre ${p} y ${y}, el stock cae mas que las ventas.`,`Puede responder a liquidacion de existencias, menor reposicion o cambio de actividad; requiere explicacion.`,`Ventas ${f1(vv)}; Inventarios ${f1(vi)}; brecha ${f1(gap)} puntos.`,y);else add(data.ok,'Inventarios acompañan las ventas',`Entre ${p} y ${y}, inventarios y ventas evolucionan de forma razonablemente compatible.`,`No se observa una divergencia material entre stock y actividad.`,`Ventas ${f1(vv)}; Inventarios ${f1(vi)}; brecha ${f1(gap)} puntos.`,y)}
      if(vv!=null&&vc!=null){const gap=vc-vv;if(gap>25)add(data.corr,'Cartera crece mas rapido que las ventas',`Entre ${p} y ${y}, los creditos comerciales aumentan por encima de las ventas.`,`Puede indicar extension de plazos o menor velocidad de cobranza.`,`Ventas ${f1(vv)}; Creditos ${f1(vc)}; brecha ${f1(gap)} puntos.`,y);else if(gap<-25)add(data.ok,'Cartera no acompaña las ventas',`Entre ${p} y ${y}, los creditos evolucionan por debajo de las ventas.`,`Es compatible con mayor contado o cobranza relativamente mas rapida; debe contrastarse con caja.`,`Ventas ${f1(vv)}; Creditos ${f1(vc)}; brecha ${f1(gap)} puntos.`,y)}
      if(vv!=null&&vp!=null){const gap=vp-vv;if(gap>25)add(data.warn,'Proveedores crecen mas rapido que las ventas',`Entre ${p} y ${y}, las obligaciones comerciales aumentan mas que la actividad.`,`Puede existir mayor dependencia del financiamiento de proveedores.`,`Ventas ${f1(vv)}; Proveedores ${f1(vp)}; brecha ${f1(gap)} puntos.`,y);else if(gap<-25)add(data.ok,'Proveedores disminuyen mas que las ventas',`Entre ${p} y ${y}, las obligaciones comerciales caen mas que la actividad.`,`Es compatible con cancelacion de deuda comercial o menor utilizacion del credito de proveedores.`,`Ventas ${f1(vv)}; Proveedores ${f1(vp)}; brecha ${f1(gap)} puntos.`,y)}
      if(vv!=null&&va!=null){const gap=va-vv;if(gap>30)add(data.warn,'Activos crecen mas que las ventas',`Entre ${p} y ${y}, los activos aumentan mucho mas que la escala comercial.`,`Debe verificarse inversion, acumulacion o activos de baja productividad.`,`Ventas ${f1(vv)}; Activos ${f1(va)}; brecha ${f1(gap)} puntos.`,y);else if(gap<-30)add(data.warn,'Ventas caen mas que los activos',`Entre ${p} y ${y}, la actividad se contrae mas que la estructura de activos.`,`Puede existir capacidad ociosa o menor productividad de los activos.`,`Ventas ${f1(vv)}; Activos ${f1(va)}; brecha ${f1(gap)} puntos.`,y)}
      if(vpa!=null&&vpat!=null&&vpa>vpat+25)add(data.corr,'Pasivo crece mas rapido que patrimonio',`Entre ${p} y ${y}, la financiacion de terceros crece mas que la base patrimonial.`,`Si se sostiene, aumenta el apalancamiento y reduce el colchon patrimonial.`,`Pasivo ${f1(vpa)}; Patrimonio ${f1(vpat)}; brecha ${f1(vpa-vpat)} puntos.`,y);
      if(a.ebitda!=null&&a.interes>0&&d.ebitda!=null&&d.interes>0){const c0=a.ebitda/a.interes,c1=d.ebitda/d.interes;if(c1<c0-1)add(data.corr,'La cobertura financiera se deteriora',`La cobertura de intereses pasa de ${f2(c0)} a ${f2(c1)} entre ${p} y ${y}.`,`La capacidad operativa para atender el costo financiero empeora.`,`Cobertura ${f2(c0)} → ${f2(c1)}.`,y);else if(c1>c0+1)add(data.ok,'La cobertura financiera mejora',`La cobertura de intereses pasa de ${f2(c0)} a ${f2(c1)} entre ${p} y ${y}.`,`La relacion entre generacion operativa e intereses evoluciona favorablemente.`,`Cobertura ${f2(c0)} → ${f2(c1)}.`,y)}
    }

    const series=[['Ventas',r,'ventas'],['Resultado bruto',r,'resultado_bruto'],['EBITDA',r,'ebitda'],['Resultado neto',r,'resultado_neto'],['Activo total',b,'total_activo'],['Pasivo total',b,'total_pasivo'],['Patrimonio neto',b,'total_patrimonio'],['Inventarios',b,'inventarios'],['Creditos comerciales',b,'creditos_ventas'],['Proveedores',b,'proveedores']];
    series.forEach(([nombre,d,key])=>{if(!d)return;const pts=years.map(y=>({y,v:val(d,key,y)})).filter(x=>x.v!=null);if(pts.length<2)return;const first=pts[0],last=pts[pts.length-1],chg=pct(last.v,first.v),dir=chg>5?'crecimiento':chg<-5?'contraccion':'estabilidad relativa';data.trend.push({nombre,first,last,chg,dir,pts})});
    return{years,data};
  }

  function css(){if(document.getElementById('auditoria-v3-css'))return;const s=document.createElement('style');s.id='auditoria-v3-css';s.textContent=`#auditoria .aud-v3{margin-top:0}.aud-v3 .intro{padding:10px 0 14px}.aud-v3 .section{margin-top:18px;border:1px solid #d9e2e0;border-radius:8px;overflow:hidden;background:#fff}.aud-v3 .section h3{margin:0;padding:11px 14px;background:#f3f6f5;color:#155f4c;font-size:14px;border-bottom:1px solid #d9e2e0}.aud-v3 .item{padding:12px 14px;border-bottom:1px solid #e8eded}.aud-v3 .item:last-child{border-bottom:0}.aud-v3 .title{font-weight:700;font-size:13px;margin-bottom:5px}.aud-v3 .line{margin:3px 0;font-size:12px;line-height:1.45}.aud-v3 .evidence{margin-top:7px;background:#f5f7f7;border-left:3px solid #9aa;padding:7px 9px;font-size:11px}.aud-v3 .crit .title{color:#b3261e}.aud-v3 .imp .title{color:#d66b00}.aud-v3 .warn .title{color:#8a7100}.aud-v3 .ok .title{color:#176b51}.aud-v3 .corr .title{color:#b3261e}.aud-v3 .empty{padding:12px 14px;color:#667;font-size:12px}.aud-v3 .summary{display:grid;grid-template-columns:repeat(5,minmax(100px,1fr));gap:10px;margin:10px 0 4px}.aud-v3 .box{border:1px solid #d9e2e0;border-left:4px solid #777;padding:10px 11px;border-radius:7px;background:#fff}.aud-v3 .box b{display:block;font-size:20px;margin-top:4px}.aud-v3 .trend{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;padding:10px}.aud-v3 .trend .t{border:1px solid #e0e6e4;border-radius:6px;padding:8px;font-size:11px}.aud-v3 .trend .t b{font-size:12px}.aud-v3 .conclusion{padding:14px;background:#eef6f2;border-left:4px solid #176b51;line-height:1.55;font-size:13px}.aud-v3 .note{font-size:11px;color:#687}.aud-v3 .period{font-size:11px;color:#667;margin-top:2px}@media(max-width:700px){.aud-v3 .summary,.aud-v3 .trend{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
  function itemHtml(x,kind){return `<div class="item ${kind}"><div class="title">${esc(x.titulo)}</div><div class="period">Periodo: <b>${esc(x.periodo||'—')}</b></div><div class="line"><b>Que muestra:</b> ${esc(x.lectura)}</div><div class="line"><b>Interpretacion:</b> ${esc(x.razon)}</div><div class="evidence"><b>Prueba / evidencia:</b> ${esc(x.evidencia)}</div></div>`}
  function section(title,arr,kind,empty){return `<div class="section"><h3>${title} <span class="note">(${arr.length})</span></h3>${arr.length?arr.map(x=>itemHtml(x,kind)).join(''):`<div class="empty">${empty}</div>`}</div>`}
  function render(){const host=document.getElementById('auditoria');if(!host)return false;const {years,data}=analizar();if(!years.length)return false;css();const c=data.crit.length,im=data.imp.length,w=data.warn.length,o=data.ok.length,co=data.corr.length;const trendHtml=data.trend.length?data.trend.map(t=>`<div class="t"><b>${esc(t.nombre)}</b><br>${esc(t.first.y)}: ${money(t.first.v)} → ${esc(t.last.y)}: ${money(t.last.v)}<br><b>${f1(t.chg)}</b> (${esc(t.dir)})</div>`).join(''):'<div class="empty">No hay suficientes valores para construir tendencias.</div>';let conclusion=c?'La informacion presenta inconsistencias o presiones financieras que deben verificarse antes de considerarla plenamente confiable. ':im?'No se observan rupturas aritmeticas principales, pero existen señales relevantes que requieren explicacion antes de concluir sobre la situacion financiera. ':'No se observan inconsistencias criticas con las pruebas ejecutadas. ';if(co)conclusion+='Las correlaciones entre ventas, inventarios, cartera, proveedores y estructura financiera permiten identificar relaciones que deben contrastarse con la informacion de soporte. ';if(data.trend.length)conclusion+='Las tendencias muestran como evolucionaron las principales magnitudes entre los periodos disponibles.';host.innerHTML=`<section class="card aud-v3"><h2>4. AUDITORIA DE COHERENCIA FINANCIERA</h2><div class="body"><div class="summary"><div class="box">Criticas<b>${c}</b></div><div class="box">Importantes<b>${im}</b></div><div class="box">Para indagar<b>${w}</b></div><div class="box">Favorables<b>${o}</b></div><div class="box">Correlaciones<b>${co}</b></div></div><div class="intro"><b>Periodos analizados:</b> ${years.join(', ')}<br><span class="note">El analisis esta separado por naturaleza del hallazgo para evitar mezclar inconsistencias, relaciones y tendencias.</span></div>${section('A. INCONSISTENCIAS / PRUEBAS CRITICAS',data.crit,'crit','No se detectaron inconsistencias aritmeticas o estructurales bajo los umbrales actuales.')}${section('B. HALLAZGOS IMPORTANTES',data.imp,'imp','No se detectaron hallazgos importantes en las pruebas ejecutadas.')}${section('C. CORRELACIONES FINANCIERAS',data.corr,'corr','No se detectaron divergencias materiales entre las cuentas comparadas.')}<div class="section"><h3>D. TENDENCIAS MULTIPERIODO</h3><div class="trend">${trendHtml}</div></div>${section('E. SEÑALES PARA INDAGAR',data.warn,'warn','No se detectaron señales que requieran indagacion adicional bajo los umbrales actuales.')}${section('F. SEÑALES FAVORABLES / CONCILIADAS',data.ok,'ok','No se registraron señales favorables o conciliaciones.')}<div class="section"><h3>G. CONCLUSION INTEGRADA</h3><div class="conclusion">${esc(conclusion)}</div></div></div></section>`;host.classList.remove('hidden');return true}
  window.AuditoriaCoherenciaV3={render,analizar};
  function enganchar(){const btn=document.getElementById('leer');if(btn&&!btn.dataset.audV3){btn.dataset.audV3='1';btn.addEventListener('click',()=>setTimeout(render,700))}const control=document.getElementById('control');if(control&&!control.dataset.audV3Obs){control.dataset.audV3Obs='1';new MutationObserver(()=>setTimeout(render,100)).observe(control,{childList:true,subtree:true})}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enganchar);else enganchar();
})();
