/* DIAGNÓSTICO EJECUTIVO CREDITICIO
   Una sola pantalla: conclusión, alertas relevantes y recomendación mínima.
   El detalle técnico queda fuera de la vista principal.
*/
(function(){
 const $=id=>document.getElementById(id), norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim(), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function rows(){const rs=[...document.querySelectorAll('#auditoria tr')].map(tr=>{const c=[...tr.children].map(x=>x.innerText.trim());return{test:c[0]||'',detail:c[2]||'',result:(c[3]||'').toUpperCase()}}).filter(x=>x.test&&x.result&&x.result!=='RESULTADO');const m=new Map;rs.forEach(x=>m.set(norm(x.test),x));return[...m.values()]}
 function classify(r){const n=norm(r.test), bad=r.result==='INCONSISTENCIA', ind=r.result==='PARA INDAGAR';if(bad)return{level:'ALERTA',text:'Existe una diferencia que no queda explicada por la prueba.'};if(ind)return{level:'ATENCION',text:'Existe una señal que merece revisión, pero no demuestra por sí sola un error.'};if(n.includes('clientes')||n.includes('inventario')||n.includes('proveedores'))return{level:'NORMAL',text:'No se detecta una inconsistencia principal en esta relación.'};return{level:'CONTROL',text:'La relación fue controlada sin una alerta principal.'}}
 function render(){const a=$('auditoria');if(!a)return;const rs=rows();if(!rs.length)return;const current=$('ejercicio')?.value||'último período';const old=$('diagnosticoEjecutivo');if(old)old.remove();const bad=rs.filter(x=>x.result==='INCONSISTENCIA'), ind=rs.filter(x=>x.result==='PARA INDAGAR');let grade='EXCELENTE',gclass='g-excellent',gtext='No se detectan alertas relevantes con la información disponible.';if(bad.length>=2){grade='MALO';gclass='g-bad';gtext='Existen varias inconsistencias relevantes que deben explicarse.'}else if(bad.length===1){grade='REGULAR';gclass='g-warn';gtext='Existe una inconsistencia relevante que requiere comprobación.'}else if(ind.length>=2){grade='REGULAR';gclass='g-warn';gtext='Existen varias señales que requieren revisión.'}else if(ind.length===1){grade='BIEN';gclass='g-good';gtext='No hay una inconsistencia principal, pero existe una señal puntual para revisar.'}
 const s=document.createElement('section');s.id='diagnosticoEjecutivo';s.className='card';let html=`<h2>CONCLUSIÓN DEL ANÁLISIS — ${esc(current)}</h2><div class="body"><div class="diag-grade ${gclass}"><div class="diag-label">RESULTADO GENERAL</div><div class="diag-value">${grade}</div><div>${gtext}</div></div>`;
 if(bad.length||ind.length){html+='<h3>LO QUE REALMENTE REQUIERE ATENCIÓN</h3><div class="exec-alerts">';[...bad,...ind].slice(0,5).forEach((x,i)=>{const c=classify(x);html+=`<div class="exec-alert ${c.level==='ALERTA'?'exec-red':'exec-yellow'}"><b>${i+1}. ${esc(x.test)}</b><span>${c.level}</span><p>${esc(c.text)}</p></div>`});html+='</div>'}else html+='<div class="exec-ok"><b>NO SE DETECTARON ALERTAS RELEVANTES.</b><br>Con la información disponible, no hay una situación que justifique solicitar documentación adicional.</div>';
 html+='<div class="exec-summary"><b>Información utilizada:</b> 3 ejercicios financieros disponibles y, cuando estén cargados, IVA y rentas.<br><b>Criterio:</b> el período actual determina la conclusión; los períodos anteriores sirven para detectar cambios y tendencias.<br><b>Documentación:</b> solo se recomienda pedir información adicional cuando una señal actual no puede resolverse con los datos disponibles.</div><details><summary>Ver análisis técnico y cálculos</summary><div class="technical-placeholder">Las pruebas cruzadas y cálculos detallados permanecen debajo de esta conclusión.</div></details></div></section>`;s.innerHTML=html;a.insertBefore(s,a.firstChild)}
 function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(render,2600))}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
