/* FLUJO DE FONDOS — VISTA CREDITICIA COMPACTA
   El período actual concentra las alertas. Los anteriores solo sirven como referencia.
*/
(function(){
 const $=id=>document.getElementById(id), norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim(), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const n=v=>{if(v==null||v==='')return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v).trim().replace(/\s/g,'');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');let x=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(x)?x:0};
 const money=x=>new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(x||0);
 function rows(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return null;return f.arrayBuffer().then(b=>{const wb=XLSX.read(b,{type:'array',raw:true,blankrows:true});const name=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0];return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:0,raw:true,blankrows:true})})}
 function run(r){if(!r)return;const C=[2,5,8],Y=['2023','2024','2025'];const cash=C.map(c=>n(r[9]?.[c])),flow=C.map(c=>n(r[185]?.[c])),clients=C.map(c=>n(r[12]?.[c])),sales=C.map(c=>n(r[63]?.[c]));const cur=2,prev=1;const checks=[{name:'Caja ↔ Flujo',diff:(cash[cur]-cash[prev])-flow[cur]},{name:'Clientes ↔ Balance',diff:flow[cur]-(clients[cur]-clients[prev])},{name:'Flujo neto ↔ movimientos',diff:flow[cur]-(n(r[158]?.[8])+n(r[184]?.[8]))}];const bad=checks.filter(x=>Math.abs(x.diff)>1);const sec=document.createElement('section');sec.className='card';sec.id='flujoCompacto';sec.innerHTML=`<h2>3. FLUJO DE FONDOS — CONTROL DEL PERÍODO ACTUAL</h2><div class="body"><div class="compact-note"><b>2025 es el período evaluado.</b> 2023 y 2024 se usan solamente para comparar evolución. No generan alertas independientes.</div><div class="flow-summary"><div><b>Caja inicial 2025</b><strong>G. ${money(cash[prev])}</strong></div><div><b>Caja final 2025</b><strong>G. ${money(cash[cur])}</strong></div><div><b>Variación según Balance</b><strong>G. ${money(cash[cur]-cash[prev])}</strong></div><div><b>Variación según Flujo</b><strong>G. ${money(flow[cur])}</strong></div></div><div class="flow-status ${bad.length?'warn':'ok'}"><b>${bad.length?'REVISAR FLUJO':'FLUJO CONCILIADO'}</b><br>${bad.length?'Existe al menos una diferencia entre el Flujo y los estados que debe explicarse.':'La variación de Caja/Bancos coincide con el Flujo del período actual.'}</div><details><summary>Ver controles del flujo</summary><table class="table"><thead><tr><th>Control</th><th>Resultado</th></tr></thead><tbody>${checks.map(x=>`<tr><td>${esc(x.name)}</td><td class="${Math.abs(x.diff)>1?'badcell':'okcell'}">${Math.abs(x.diff)>1?'Diferencia G. '+money(x.diff):'Conciliado'}</td></tr>`).join('')}</tbody></table></details></div></section>`;const a=$('auditoria');if(a){a.classList.remove('hidden');a.insertBefore(sec,a.firstChild)}else document.body.appendChild(sec)}
 function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>rows().then(run),150));}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
