/* ETAPA 4 - PRUEBAS CRUZADAS */
(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  const fmt=n=>n===null||n===undefined||n===''?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(Number(n)||0);
  const pct=n=>n===null||n===undefined||!Number.isFinite(n)?'—':`${n.toFixed(1)}%`;
  const num=v=>{if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');const n=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(n)?n:null;};
  const years=['2023','2024','2025'],cols=[2,5,8];
  const aliases={
    'disponible (caja y bancos)':'caja','inventario':'inventario','anticipos a proveedores':'anticipos',
    'creditos comerciales - cp (clientes)':'clientes','total activo':'activo','activo fijo (bruto)':'ppe',
    'deudas financieras - cp':'deudaCp','deudas financieras - lp':'deudaLp','deudas comerciales - cp (proveedores)':'proveedores',
    'acreedores varios':'acreedores','total pasivo':'pasivo','capital':'capital','total patrimonio neto':'patrimonio',
    'resultado del ejercicio':'resultado','ventas netas':'ventas','costo de ventas':'costo','resultado bruto comercial principal':'bruto',
    'gastos operativos, administrativos y de ventas':'gastos','gastos operativos, administrativos y de ahorros y creditos':'gastosAhorros',
    'ebitda (flujo operativo puro/caja real)':'ebitda','intereses financieros pagados':'intereses','resultado antes de impuesto':'antesImpuesto'
  };
  const flujoAliases={
    'variacion neta de caja':'varCaja','variacion cuentas a cobrar comerciales cp':'varClientes','variacion inventario + anticipos a proveedores':'varInventario',
    'variacion cuentas a pagar comerciales cp':'varProveedores','variacion activo fijo (inversiones y compras)':'capex','nuevas deudas financieras cp':'nuevasDeudaCp',
    'nuevas deudas financieras lp':'nuevasDeudaLp','pago de deudas financieras cp':'pagoDeudaCp','pago deudas financieras cp':'pagoDeudaCp',
    'pago deudas financieras lp':'pagoDeudaLp','generacion neta operativa':'operativo','generacion (aplicacion) neta operativa':'operativo',
    'generacion (aplicacion) neta no operativa':'noOperativo'
  };
  function readRows(){
    const file=$('archivoUnico')?.files?.[0];
    if(!file||!window.XLSX)throw new Error('No se pudo acceder al archivo Excel.');
    return file.arrayBuffer().then(buf=>{const wb=XLSX.read(buf,{type:'array',cellDates:true,raw:true,blankrows:true});const name=wb.SheetNames.find(n=>norm(n)==='ee ff y eerr')||wb.SheetNames[0];return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:true});});
  }
  function extract(rows,map,start,end){const d={};Object.entries(map).forEach(([label,key])=>{const target=norm(label);let row=-1;for(let r=start;r<end;r++){const c=[rows[r]?.[1],rows[r]?.[0],rows[r]?.[2]].map(norm);if(c.includes(target)){row=r;break;}}d[key]=row<0?null:cols.map(c=>num(rows[row]?.[c]));});return d;}
  const v=(d,k,i)=>d[k]?.[i]??null;
  const has=(x)=>x!==null&&x!==undefined&&Number.isFinite(x);
  const activeYears=(d)=>years.map((y,i)=>({y,i})).filter(({i})=>Object.keys(d).some(k=>has(v(d,k,i))&&v(d,k,i)!==0));
  function status(s){return s==='CONCILIADO'?'okcell':s==='OBSERVACIÓN'?'warncell':s==='PARA INDAGAR'?'warncell':'badcell';}
  function row(test,relation,detail,result){return `<tr><td><b>${esc(test)}</b></td><td>${esc(relation)}</td><td>${esc(detail)}</td><td class="${status(result)}"><b>${esc(result)}</b></td></tr>`;}
  function days(avg,base){return avg===null||!has(base)||base===0?null:avg/base*365;}
  function clientSales(d,i,prev){const ar=v(d,'clientes',i),sales=v(d,'ventas',i);if(!has(ar)||!has(sales)||sales===0)return row('1. Clientes ↔ Ventas','Clientes y ventas deben guardar una relación económica verificable.','No existen cuentas por cobrar y ventas suficientes para calcular el indicador.','SIN DATOS');const avg=prev!==null&&has(v(d,'clientes',prev))?(ar+v(d,'clientes',prev))/2:ar;const dc=days(avg,sales),ratio=ar/sales;let result=dc!==null&&dc>180?'PARA INDAGAR':'CORRELACIÓN';let detail=`Clientes ${fmt(ar)} · Ventas ${fmt(sales)} · Clientes/Ventas ${pct(ratio*100)} · Días estimados ${dc===null?'—':dc.toFixed(1)}`;if(prev!==null&&has(v(d,'clientes',prev))&&has(v(d,'ventas',prev))&&v(d,'ventas',prev)!==0){const prevRatio=v(d,'clientes',prev)/v(d,'ventas',prev);detail+=` · Período anterior ${pct(prevRatio*100)}`;}return row('1. Clientes ↔ Ventas','Clientes / Ventas y evolución del plazo implícito.',detail,result);}
  function inventoryCost(d,i,prev){const inv=v(d,'inventario',i),cost=v(d,'costo',i);if(!has(inv)||!has(cost)||cost===0)return row('2. Inventario ↔ Costo de ventas','Inventario debe guardar relación con el nivel y rotación del costo.','No existen inventario y costo de ventas suficientes.','SIN DATOS');const ratio=inv/cost,turn=cost/inv;let result=ratio>0.5?'PARA INDAGAR':'CORRELACIÓN';let detail=`Inventario ${fmt(inv)} · Costo de ventas ${fmt(cost)} · Inventario/Costo ${pct(ratio*100)} · Rotación aproximada ${turn.toFixed(2)}x`;if(prev!==null&&has(v(d,'inventario',prev))&&has(v(d,'costo',prev))&&v(d,'costo',prev)!==0)detail+=` · Período anterior ${pct((v(d,'inventario',prev)/v(d,'costo',prev))*100)}`;return row('2. Inventario ↔ Costo de ventas','Nivel de inventario frente al costo de ventas.',detail,result);}
  function suppliersPurchases(d,i,prev){const inv=v(d,'inventario',i),inv0=prev!==null?v(d,'inventario',prev):null,cost=v(d,'costo',i),ap=v(d,'proveedores',i),ap0=prev!==null?v(d,'proveedores',prev):null;if(!has(inv)||!has(cost)||!has(ap)||!has(inv0)||!has(ap0))return row('3. Proveedores ↔ Compras reconstruidas','Compras ≈ Costo de ventas + ΔInventario; su evolución debe poder relacionarse con proveedores.','No existen saldos consecutivos suficientes para reconstruir compras.','SIN DATOS');const purchases=cost+(inv-inv0),deltaAp=ap-ap0,coverage=purchases!==0?deltaAp/purchases:null;let result=Math.abs(deltaAp)>Math.abs(purchases)*0.5?'PARA INDAGAR':'CORRELACIÓN';return row('3. Proveedores ↔ Compras reconstruidas','Compras ≈ Costo de ventas + ΔInventario.',`Compras reconstruidas ${fmt(purchases)} · Variación proveedores ${fmt(deltaAp)} · Cobertura del movimiento ${coverage===null?'—':pct(coverage*100)}. La diferencia no implica error: puede incluir pagos, crédito, anticipos y otros acreedores.`,result);}
  function debtInterest(d,i,prev){const debt=(v(d,'deudaCp',i)||0)+(v(d,'deudaLp',i)||0),interest=v(d,'intereses',i);if(!has(interest)||(!has(v(d,'deudaCp',i))&&!has(v(d,'deudaLp',i))))return row('4. Deuda ↔ Intereses','El costo financiero debe guardar relación con la existencia y evolución de deuda.','No existen datos suficientes de deuda financiera e intereses pagados.','SIN DATOS');const debt0=prev!==null?((v(d,'deudaCp',prev)||0)+(v(d,'deudaLp',prev)||0)):null;const avg=has(debt0)?(debt+debt0)/2:debt;const rate=avg>0?interest/avg:null;let result=debt===0&&interest>0?'PARA INDAGAR':rate!==null&&rate>0.30?'PARA INDAGAR':'CORRELACIÓN';return row('4. Deuda ↔ Intereses','Intereses pagados frente al saldo medio aproximado de deuda.',`Deuda final ${fmt(debt)} · Intereses pagados ${fmt(interest)} · Tasa implícita aproximada ${rate===null?'—':pct(rate*100)}. La tasa implícita no sustituye el contrato ni distingue períodos de devengamiento.`,result);}
  function cashFlow(d,f,i,prev){const cash=v(d,'caja',i),cash0=prev!==null?v(d,'caja',prev):null,flow=v(f,'varCaja',i);if(!has(cash)||!has(cash0)||!has(flow))return row('5. Caja ↔ Flujo de fondos','Caja final − Caja inicial = Variación neta de caja.','No existen saldos de caja y variación de flujo suficientes.','SIN DATOS');const diff=(cash-cash0)-flow;return row('5. Caja ↔ Flujo de fondos','Caja final − Caja inicial = Variación neta de caja.',`Caja inicial ${fmt(cash0)} · Caja final ${fmt(cash)} · Variación calculada ${fmt(cash-cash0)} · Flujo ${fmt(flow)} · Diferencia ${fmt(diff)}`,Math.abs(diff)<=1?'CONCILIADO':'INCONSISTENCIA');}
  function ppeCapex(d,f,i,prev){const ppe=v(d,'ppe',i),ppe0=prev!==null?v(d,'ppe',prev):null,capex=v(f,'capex',i);if(!has(ppe)||!has(ppe0)||!has(capex))return row('6. PPE ↔ CAPEX ↔ Financiamiento','El aumento del activo fijo debe poder relacionarse con inversiones/capex y sus fuentes.','No existen PPE consecutivo y CAPEX suficientes.','SIN DATOS');const delta=ppe-ppe0,absCapex=Math.abs(capex);const diff=delta-absCapex;let result=Math.abs(diff)<=1?'CONCILIADO':'PARA INDAGAR';return row('6. PPE ↔ CAPEX ↔ Financiamiento','ΔActivo fijo bruto frente a inversión/compra de activo fijo.',`PPE inicial ${fmt(ppe0)} · PPE final ${fmt(ppe)} · Aumento ${fmt(delta)} · CAPEX del flujo ${fmt(capex)} · Diferencia ${fmt(diff)}. La diferencia puede obedecer a ventas, bajas, reclasificaciones o activos adquiridos por vías no reflejadas en la línea evaluada.`,result);}
  function financing(d,f,i,prev){const debt=(v(d,'deudaCp',i)||0)+(v(d,'deudaLp',i)||0),debt0=prev!==null?((v(d,'deudaCp',prev)||0)+(v(d,'deudaLp',prev)||0)):null,newDebt=(v(f,'nuevasDeudaCp',i)||0)+(v(f,'nuevasDeudaLp',i)||0);if(!has(debt0)||(!has(v(f,'nuevasDeudaCp',i))&&!has(v(f,'nuevasDeudaLp',i))))return row('7. Inversión ↔ Fuentes de financiamiento','El aumento de inversión debe contrastarse con deuda nueva, capital y generación interna.','No existen datos suficientes para identificar la fuente del financiamiento.','SIN DATOS');const delta=debt-debt0;return row('7. Inversión ↔ Fuentes de financiamiento','Variación de deuda frente a nuevas deudas reportadas.',`Deuda inicial ${fmt(debt0)} · Deuda final ${fmt(debt)} · Aumento neto ${fmt(delta)} · Nuevas deudas reportadas ${fmt(newDebt)}. Esta prueba identifica una fuente posible, no demuestra por sí sola el destino de los fondos.`,Math.abs(delta-newDebt)<=1?'CONCILIADO':'CORRELACIÓN');}
  function render(d,f){const valid=activeYears(d);let html='<section class="card" id="pruebasCruzadasSection"><h2>6. PRUEBAS CRUZADAS</h2><div class="body"><div class="audit-current"><b>CONTROL ESPECÍFICO</b><br>Se relacionan cuentas de Balance, Estado de Resultados y Flujo de Fondos para detectar relaciones económicas que no se prueban mirando cada estado de forma aislada. Esta etapa no emite riesgo crediticio.</div>';valid.filter(x=>x.i>0).forEach(({y,i})=>{const prev=i-1;html+=`<div class="alert ok"><strong>${y} — PRUEBAS CRUZADAS</strong><div>Comparación con ${years[prev]} y con las relaciones disponibles del período.</div></div><table class="table"><thead><tr><th>Prueba</th><th>Relación</th><th>Conciliación / análisis</th><th>Resultado</th></tr></thead><tbody>${clientSales(d,i,prev)}${inventoryCost(d,i,prev)}${suppliersPurchases(d,i,prev)}${debtInterest(d,i,prev)}${cashFlow(d,f,i,prev)}${ppeCapex(d,f,i,prev)}${financing(d,f,i,prev)}</tbody></table>`;});if(!valid.some(x=>x.i>0))html+='<div class="alert warn"><b>SIN DATOS SUFICIENTES</b><div>No existen al menos dos períodos con información contable para ejecutar pruebas cruzadas.</div></div>';html+='<div class="audit-current"><b>CRITERIO</b><br><b>CONCILIADO</b> = la relación matemática evaluada cuadra. <b>CORRELACIÓN</b> = existe relación económica útil, pero no demuestra por sí sola un error o una causa. <b>PARA INDAGAR</b> = la relación presenta una señal que requiere explicación documental o gerencial. <b>INCONSISTENCIA</b> = la relación matemática evaluada no cuadra.</div></div></section>';const old=$('pruebasCruzadasSection');if(old)old.remove();$('auditoria').insertAdjacentHTML('beforeend',html);}
  async function run(){try{const rows=await readRows();const d=extract(rows,aliases,9,90);const f=extract(rows,flujoAliases,144,187);render(d,f);}catch(e){const old=$('pruebasCruzadasSection');if(old)old.remove();$('auditoria').insertAdjacentHTML('beforeend',`<section class="card" id="pruebasCruzadasSection"><h2>6. PRUEBAS CRUZADAS</h2><div class="body"><div class="alert crit"><b>ERROR EN PRUEBAS CRUZADAS:</b> ${esc(e.message)}</div></div></section>`);}}
  function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(run,320));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
