/* MOTOR DIAGNÓSTICO FINANCIERO FINAL
   - Último período disponible = período actual.
   - Períodos anteriores = tendencia; no generan alertas independientes.
   - Cada señal: cálculo -> relación -> significado -> impacto crediticio -> acción.
   - No clasifica deuda comercial como financiera.
*/
(function(){
 const $=id=>document.getElementById(id);
 const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const N=v=>{if(v==null||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');const n=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(n)?n:null};
 const money=n=>n==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(n);
 const pct=n=>n==null||!Number.isFinite(n)?'—':(n*100).toFixed(1)+'%';
 const days=n=>n==null||!Number.isFinite(n)?'—':n.toFixed(1)+' días';
 const growth=(a,b)=>a==null||b==null||b===0?null:(a-b)/Math.abs(b);
 const aliases={
  activo:['total activo'],pasivo:['total pasivo'],patrimonio:['total patrimonio neto','patrimonio neto'],
  caja:['disponible (caja y bancos)','disponible caja y bancos','caja y bancos','disponible'],
  clientes:['creditos comerciales - cp (clientes)','creditos comerciales cp (clientes)'],
  inventario:['inventario'],proveedores:['deudas comerciales - cp (proveedores)','deudas comerciales cp (proveedores)'],
  acreedores:['acreedores varios'],impuestos:['impuestos por pagar','tributos por pagar'],
  deudaCP:['deudas financieras - cp','deudas financieras cp'],deudaLP:['deudas financieras - lp','deudas financieras lp'],
  ventas:['ventas netas'],costo:['costo de ventas'],intereses:['intereses financieros pagados'],
  resultado:['resultado neto total del ejercicio','resultado neto','resultado del ejercicio'],
  ebitda:['ebitda (flujo operativo puro/caja real)','ebitda'],
  flowOp:['generacion (aplicacion) neta operativa'],flowCaja:['variacion neta de caja'],
  flowClientes:['variacion cuentas a cobrar comerciales cp','variacion cuentas a cobrar comerciales'],
  flowInventario:['variacion inventario + anticipos a proveedores'],flowProveedores:['variacion cuentas a pagar comerciales cp'],
  flowDeudaFinCP:['nuevas deudas financieras cp'],flowDeudaFinLP:['nuevas deudas financieras lp'],
  flowDeudaComLP:['nuevas deudas comerciales lp'],flowPagoFinCP:['pago deudas financieras cp'],flowPagoFinLP:['pago deudas financieras lp'],
  flowPagoComLP:['pago deudas comerciales lp'],flowActivoFijo:['variacion activo fijo (inversiones y compras)']
 };
 function yearOf(v){const m=String(v??'').match(/(?:19|20)\d{2}/);return m?m[0]:null}
 function read(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return Promise.resolve(null);return f.arrayBuffer().then(b=>{const wb=XLSX.read(b,{type:'array',raw:true,blankrows:true});const name=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:true});let yearCols=[];for(let r=0;r<Math.min(rows.length,15);r++){const found=[];for(let c=0;c<(rows[r]?.length||0);c++){const y=yearOf(rows[r][c]);if(y)found.push([c,y])}if(found.length>=2){yearCols=found;break}}if(!yearCols.length){yearCols=[2,5,8].map(c=>[c,yearOf(rows[4]?.[c])]).filter(x=>x[1])}yearCols.sort((a,b)=>a[0]-b[0]);const years=yearCols.map(x=>x[1]);const sections={balance:[0,Math.min(rows.length,70)],resultados:[55,Math.min(rows.length,115)],flujo:[110,rows.length]};function findRow(key,section){const want=aliases[key].map(norm),[a,z]=sections[section];for(let r=a;r<z;r++){const s=norm(rows[r]?.[1]??rows[r]?.[0]);if(want.includes(s))return r}for(let r=a;r<z;r++){const s=norm(rows[r]?.[1]??rows[r]?.[0]);if(want.some(x=>s===x||s.startsWith(x+' ')||s.endsWith(' '+x)))return r}return -1}const d={years,file:f.name,name,rows,yearCols};for(const[k]of Object.entries(aliases)){let sec=['flowOp','flowCaja','flowClientes','flowInventario','flowProveedores','flowDeudaFinCP','flowDeudaFinLP','flowDeudaComLP','flowPagoFinCP','flowPagoFinLP','flowPagoComLP','flowActivoFijo'].includes(k)?'flujo':(['ventas','costo','intereses','resultado','ebitda'].includes(k)?'resultados':'balance');const r=findRow(k,sec);d[k]=r<0?null:yearCols.map(([c])=>N(rows[r]?.[c]))}return d})}
 const v=(d,k,i)=>d[k]?.[i]??null, has=x=>x!=null&&Number.isFinite(x);
 function analyze(d){const n=d.years.length,i=n-1,p=n-2,b=n-3,a=[];const cur=d.years[i],prev=p>=0?d.years[p]:null,base=b>=0?d.years[b]:null;const add=(level,title,calc,meaning,rel,action)=>a.push({level,title,calc,meaning,rel,action});
  const act=v(d,'activo',i),pas=v(d,'pasivo',i),pat=v(d,'patrimonio',i),sales=v(d,'ventas',i),salesP=v(d,'ventas',p),cost=v(d,'costo',i),costP=v(d,'costo',p),cli=v(d,'clientes',i),cliP=v(d,'clientes',p),inv=v(d,'inventario',i),invP=v(d,'inventario',p),prov=v(d,'proveedores',i),provP=v(d,'proveedores',p),cash=v(d,'caja',i),cashP=v(d,'caja',p),res=v(d,'resultado',i),resP=v(d,'resultado',p),debt=(v(d,'deudaCP',i)||0)+(v(d,'deudaLP',i)||0),debtP=p>=0?(v(d,'deudaCP',p)||0)+(v(d,'deudaLP',p)||0):null,inter=v(d,'intereses',i),flowCli=v(d,'flowClientes',i),flowInv=v(d,'flowInventario',i),flowProv=v(d,'flowProveedores',i),flowOp=v(d,'flowOp',i),newFin=(v(d,'flowDeudaFinCP',i)||0)+(v(d,'flowDeudaFinLP',i)||0),newCom=v(d,'flowDeudaComLP',i),payFin=(v(d,'flowPagoFinCP',i)||0)+(v(d,'flowPagoFinLP',i)||0),payCom=v(d,'flowPagoComLP',i),capex=v(d,'flowActivoFijo',i);
  if(has(act)&&has(pas)&&has(pat)){const diff=act-pas-pat;if(Math.abs(diff)>Math.max(Math.abs(act)*.005,1))add('CRÍTICO','Balance: ecuación patrimonial no cierra',`Activo G. ${money(act)} − Pasivo G. ${money(pas)} − Patrimonio G. ${money(pat)} = diferencia G. ${money(diff)}.`,`El balance presentado no permite determinar correctamente la estructura patrimonial hasta explicar la diferencia.`,`Activo ↔ Pasivo ↔ Patrimonio`,`No aumentar la exposición hasta identificar y corregir o explicar la diferencia.`)}
  if(has(sales)&&has(salesP)&&salesP!==0){const g=growth(sales,salesP);if(g<=-.15)add(g<=-.30?'ALTA':'MEDIA','Ventas: deterioro de actividad',`Ventas ${cur}: G. ${money(sales)} vs ${prev}: G. ${money(salesP)} (${pct(g)}).`,`La actividad disminuyó. El riesgo aumenta si también caen el resultado y la generación operativa.`,`Ventas ↔ Resultado ↔ Flujo operativo ↔ IVA`,`Si la caída es confirmada y afecta generación de fondos, considerar reducción de exposición.`)}
  if(has(cli)&&has(sales)&&sales>0){const d0=cli/sales*365,dP=has(cliP)&&has(salesP)&&salesP>0?cliP/salesP*365:null,cg=has(cliP)&&cliP!==0?growth(cli,cliP):null,sg=has(salesP)&&salesP!==0?growth(sales,salesP):null,delta=has(cliP)?cli-cliP:null,flowOK=has(flowCli)&&has(delta)&&Math.abs(flowCli-delta)<=1;if(d0>60||(dP!=null&&d0>dP+30)||(cg!=null&&sg!=null&&cg>sg+0.20)){let c=`Clientes G. ${money(cli)} ÷ Ventas G. ${money(sales)} × 365 = ${days(d0)}.`;if(dP!=null)c+=` ${prev}: ${days(dP)}.`;if(cg!=null&&sg!=null)c+=` Clientes ${pct(cg)} vs ventas ${pct(sg)}.`;if(delta!=null)c+=` Aumento del saldo: G. ${money(delta)}.`;if(flowOK)c+=` El Flujo registra la misma variación: G. ${money(flowCli)}.`;const m=cg!=null&&sg!=null&&cg>sg*3?`Los créditos a clientes crecieron mucho más rápido que las ventas. En términos sencillos, una parte mayor de las ventas quedó pendiente de cobro: G. ${money(delta||0)} pasó a financiar clientes en lugar de convertirse en efectivo. Esto puede aumentar la necesidad de capital de trabajo; no demuestra por sí solo incobrabilidad.`:`El saldo de clientes aumentó en relación con las ventas. La señal no demuestra un problema por sí sola; indica que una mayor parte del capital quedó temporalmente en cuentas por cobrar.`;add('MEDIA','Clientes: mayor plazo de cobro',c,m,'Clientes ↔ Ventas ↔ Flujo de cuentas a cobrar ↔ Caja','Si el Flujo explica la variación, no pedir documentación adicional por esta señal. Si no la explica, revisar y recién después pedir detalle de deuda de clientes.')}}
  if(has(inv)&&has(cost)&&cost>0){const id=inv/cost*365,idP=has(invP)&&has(costP)&&costP>0?invP/costP*365:null;if(id>180||(idP!=null&&id>idP+45))add((has(sales)&&has(salesP)&&sales<salesP)?'ALTA':'MEDIA','Inventario: posible acumulación',`Inventario G. ${money(inv)} ÷ Costo de ventas G. ${money(cost)} × 365 = ${days(id)}.`+(idP!=null?` ${prev}: ${days(idP)}.`:''),`El stock representa capital que todavía no se convirtió en ventas y efectivo. El riesgo es mayor si las ventas disminuyen o el flujo muestra consumo de fondos.`,`Inventario ↔ Costo de ventas ↔ Ventas ↔ Flujo ↔ Caja`,`Si la acumulación no se explica por crecimiento normal, revisar inventario; no pedir documentación adicional si los estados y el flujo la explican.`)}
  if(has(prov)&&has(provP)&&has(cost)&&has(inv)&&has(invP)){const compras=cost+(inv-invP),delta=prov-provP;if(compras>0&&delta<0&&Math.abs(delta)>compras*.25)add('MEDIA','Proveedores: compras con reducción de deuda',`Compras aproximadas G. ${money(compras)} = Costo de ventas G. ${money(cost)} + aumento de inventario G. ${money(inv-invP)}. Proveedores disminuyeron G. ${money(Math.abs(delta))}.`,`La empresa compró bienes por un importe relevante mientras redujo su deuda con proveedores. Eso puede ser normal si pagó las compras con caja u otra financiación; el control busca comprobar cuál fue la fuente.`,`Costo de ventas ↔ Inventario ↔ Proveedores ↔ Caja ↔ Deuda`,`Primero comprobar el Flujo. Solo si el financiamiento/pago no cierra, pedir detalle de deuda con proveedores.`)}
  if(has(pas)&&has(sales)&&has(pasP)&&has(salesP)){const gp=growth(pas,pasP),gs=growth(sales,salesP),r=pas/sales,rp=pasP/salesP;if(gs>0.15&&gp<-0.15&&r<rp*.70)add('ALTA','Pasivo: posible omisión o reducción que requiere explicación',`Ventas ${pct(gs)}; Pasivo ${pct(gp)}; Pasivo/Ventas ${pct(rp)} → ${pct(r)}.`,`El negocio crece mientras las obligaciones registradas disminuyen con fuerza. No demuestra pasivo omitido: puede existir pago, refinanciación, reclasificación o cambio de estructura.`,`Ventas ↔ Pasivo ↔ Proveedores ↔ Acreedores ↔ Impuestos ↔ Deuda ↔ Flujo`,`Primero comprobar los movimientos ya presentados. Si no cierran, pedir únicamente información específica sobre obligaciones no explicadas.`)}
  if(has(newCom)&&Math.abs(newCom)>0){const totalPas=has(pas)?pas:0;add('MEDIA','Nueva deuda comercial de largo plazo detectada',`El Flujo registra Nuevas Deudas Comerciales LP por G. ${money(newCom)}.`,`Es una obligación comercial de largo plazo, no deuda financiera bancaria. El sistema debe comprobar si tiene correspondencia en el Pasivo y qué financió.`,`Flujo ↔ Deudas comerciales LP ↔ Pasivo ↔ Activo adquirido/inventario ↔ Caja`,`No pedir referencia bancaria por este concepto automáticamente. Si no tiene correspondencia razonable en el Balance o su destino no puede explicarse, generar alerta específica de conciliación.`)}
  if(has(inter)&&inter!==0&&debt===0)add('ALTA','Intereses con deuda financiera cero al cierre',`Intereses G. ${money(inter)} y deuda financiera CP+LP al cierre G. 0.`,`Puede tratarse de deuda cancelada durante el año, intereses devengados previamente o una obligación clasificada en otra cuenta.`,`Intereses ↔ Deuda financiera ↔ Nuevas deudas ↔ Pagos de deuda`,`Primero comprobar los movimientos del año. Solo si no cierran, pedir detalle de deuda o referencia bancaria.`)
  if(has(res)&&res>0&&has(cash)&&has(cashP)&&cash<cashP){const drop=cashP-cash;add('MEDIA','Resultado positivo pero Caja disminuye',`Resultado G. ${money(res)}; Caja/Bancos G. ${money(cashP)} → G. ${money(cash)}; disminución G. ${money(drop)}.`,`La utilidad contable no significa que el mismo importe esté disponible en efectivo. El sistema debe identificar qué movimientos absorbieron la caja.`,`Resultado ↔ Clientes ↔ Inventario ↔ Proveedores ↔ Deuda ↔ Flujo ↔ Caja`,`Si el puente de efectivo explica la disminución, no pedir documentación adicional. Si queda una diferencia material, revisar primero el flujo.`)}
  if(has(flowOp)&&has(res)&&flowOp<0&&res>0)add('ALTA','Resultado positivo con flujo operativo negativo',`Resultado neto G. ${money(res)}; Generación (aplicación) neta operativa G. ${money(flowOp)}.`,`La empresa muestra utilidad contable pero la operación consume efectivo. Esto puede ocurrir por aumento de clientes, inventarios u otras necesidades de capital de trabajo y es relevante para la capacidad de pago.`,`Resultado ↔ Capital de trabajo ↔ Flujo operativo ↔ Caja`,`Identificar automáticamente qué cuentas consumieron el efectivo antes de decidir sobre la línea.`)
  if(has(newFin)||has(payFin)||has(newCom)||has(payCom)){const parts=[];if(newFin)parts.push(`nueva deuda financiera G. ${money(newFin)}`);if(payFin)parts.push(`pagos financieros G. ${money(payFin)}`);if(newCom)parts.push(`nueva deuda comercial LP G. ${money(newCom)}`);if(payCom)parts.push(`pagos comerciales LP G. ${money(payCom)}`);if(parts.length)add('MEDIA','Financiación del período',parts.join('; ')+'.','El sistema detecta cómo se financió o canceló parte de la actividad. La existencia de financiación no es negativa por sí sola; importa su magnitud, destino y capacidad de pago.','Nuevas deudas ↔ Pagos de deuda ↔ Pasivo ↔ Caja ↔ Flujo operativo','Usar esta información para la conclusión global; no pedir documentación solo porque exista nueva deuda.')}
  if(has(capex)&&Math.abs(capex)>0&&has(newFin)&&Math.abs(capex)>Math.abs(newFin)*1.25)add('MEDIA','Inversiones mayores que nueva deuda financiera',`Inversiones en activo fijo G. ${money(Math.abs(capex))}; nueva deuda financiera G. ${money(newFin)}.`,`La inversión no parece financiarse principalmente con nueva deuda financiera. Puede haberse financiado con caja, deuda comercial, patrimonio o recursos operativos.`,`Activo fijo ↔ Flujo de inversiones ↔ Deuda ↔ Caja ↔ Patrimonio`,`Determinar automáticamente la fuente restante antes de pedir documentación.`)
  return {current:cur,prev,base,a};}
 function grade(a){const c={CRÍTICO:0,ALTA:1,MEDIA:2};if(a.some(x=>x[0]==='CRÍTICO'))return ['CRÍTICO','Existe una inconsistencia que debe aclararse antes de decidir la exposición.'];const h=a.filter(x=>x.level==='ALTA').length,m=a.filter(x=>x.level==='MEDIA').length;if(h>=2)return ['MALO','Existen varias señales relevantes en el período actual.'];if(h===1)return ['REGULAR','Existe una señal relevante que debe comprobarse antes de aumentar la exposición.'];if(m>=2)return ['REGULAR','Existen varias señales actuales, aunque no prueban por sí solas una inconsistencia.'];if(m===1)return ['BIEN','Existe una señal puntual que debe considerarse, sin evidencia suficiente de una inconsistencia grave.'];return ['EXCELENTE','No se detectaron señales relevantes con la información disponible.']}
 function render(d){if(!d)return;const out=analyze(d),g=grade(out.a),cliente=$('cliente')?.value||'';$('ejercicio').value=out.current;$('periodos').value=d.years.join(', ');const escL=esc;let html=`<div class="audit-current"><b>DIAGNÓSTICO FINANCIERO DEL PERÍODO ACTUAL: ${escL(out.current)}</b><br>Los períodos anteriores (${escL([out.prev,out.base].filter(Boolean).join(' y '))}) se utilizan únicamente para medir tendencia y deterioro. <b>No generan alertas independientes.</b></div><div class="grade ${g[0]==='CRÍTICO'||g[0]==='MALO'?'g-bad':g[0]==='REGULAR'?'g-warn':'g-good'}"><strong>${g[0]}</strong><span>${g[1]}</span></div>`;if(!out.a.length)html+=`<div class="alert ok"><strong>Sin señales relevantes</strong><div>Con la documentación cargada, los controles no encontraron una desviación que supere los umbrales definidos.</div></div>`;out.a.forEach((x,k)=>{html+=`<div class="finding ${x.level==='CRÍTICO'||x.level==='ALTA'?'finding-high':'finding-med'}"><h3>${k+1}. ${escL(x.title)} <small>${x.level}</small></h3><p><b>Qué calculó:</b> ${escL(x.calc)}</p><p><b>Qué significa:</b> ${escL(x.meaning)}</p><p><b>Cuentas relacionadas:</b> ${escL(x.rel)}</p><p><b>Qué hacer:</b> ${escL(x.action)}</p></div>`});html+=`<div class="audit-current"><b>ALCANCE</b><br>El resultado es un control de coherencia y análisis crediticio sobre la información presentada. Una alerta no afirma por sí sola incumplimiento contable ni fraude; indica una situación que requiere explicación o consideración crediticia.</div>`;$('controlBody').innerHTML=html;$('control').classList.remove('hidden')}
 function init(){const btn=$('leer');if(!btn)return;btn.addEventListener('click',()=>read().then(render));}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();