/* MOTOR PRINCIPAL DE CONTROLES FINANCIEROS
   Objetivo: detectar anomalías útiles para análisis crediticio a partir de 3 balances,
   3 estados de resultados y flujo comparativo. No sustituye el criterio profesional.
*/
(function(){
  const $=id=>document.getElementById(id);
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const N=v=>{if(v==null||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');let x=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(x)?x:null};
  const money=x=>x==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(x);
  const pct=x=>x==null?'—':(x*100).toFixed(1)+'%';
  const years=[2023,2024,2025], cols=[2,5,8];
  const aliases={
   activo:['total activo','activo total'],pasivo:['total pasivo','pasivo total'],patrimonio:['patrimonio neto','total patrimonio neto','patrimonio'],
   caja:['disponible (caja y bancos)','disponible caja y bancos','caja y bancos','disponible','caja'],clientes:['creditos comerciales - cp (clientes)','creditos comerciales cp (clientes)','creditos comerciales - cp','creditos comerciales cp','clientes'],
   inventario:['inventario','inventarios'],ppe:['activo fijo (bruto)','activo fijo bruto','activo fijo'],proveedores:['deudas comerciales - cp (proveedores)','deudas comerciales cp (proveedores)','deudas comerciales - cp','deudas comerciales cp','proveedores'],
   acreedores:['acreedores varios','otras cuentas por pagar','otros acreedores'],impuestos:['impuestos por pagar','tributos por pagar','impuestos y tasas por pagar'],deudaCp:['deudas financieras - cp','deudas financieras cp','deuda financiera - cp','deuda financiera cp'],deudaLp:['deudas financieras - lp','deudas financieras lp','deuda financiera - lp','deuda financiera lp'],
   ventas:['ventas netas','ventas'],costo:['costo de ventas','costos de ventas'],resultadoBruto:['resultado bruto'],resultadoOperativo:['resultado operativo','resultado de operaciones'],intereses:['intereses financieros pagados','intereses financieros','intereses pagados'],resultado:['resultado neto','resultado del ejercicio','ganancia del ejercicio','perdida del ejercicio'],depreciacion:['depreciaciones','depreciacion y amortizacion','depreciacion'],
   capital:['capital social','capital'],reservas:['reservas'],resultadosAcum:['resultados acumulados']
  };
  const flujo={varCaja:['variacion neta de caja','variacion neta caja','variacion de caja','variacion neta del efectivo'],capex:['variacion activo fijo (inversiones y compras)','variacion activo fijo inversiones y compras','inversiones y compras de activo fijo','compras de activo fijo'],cobrosClientes:['cobros de clientes','cobros por ventas'],pagosProveedores:['pagos a proveedores','pagos por compras'],nuevasDeuda:['nuevas deudas financieras','nuevas deudas'],pagosDeuda:['pagos de deudas financieras','pagos de deuda']};
  function read(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return Promise.resolve(null);return f.arrayBuffer().then(buf=>{const wb=XLSX.read(buf,{type:'array',raw:true,blankrows:true});const name=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0];return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:true});});}
  function find(rows,labels){const ws=labels.map(norm);for(let r=0;r<rows.length;r++){const c=[0,1,2,3].map(i=>norm(rows[r]?.[i])).filter(Boolean);if(ws.some(w=>c.includes(w)))return r}for(let r=0;r<rows.length;r++){const c=[0,1,2,3].map(i=>norm(rows[r]?.[i])).filter(Boolean);if(ws.some(w=>c.some(z=>z===w||z.startsWith(w+' ')||z.endsWith(' '+w))))return r}return -1}
  function extract(rows,map){const d={};Object.entries(map).forEach(([k,labels])=>{const r=find(rows,labels);d[k]=r<0?null:cols.map(c=>N(rows[r]?.[c]))});return d}
  const v=(d,k,i)=>d[k]?.[i]??null, h=x=>x!=null&&Number.isFinite(x);
  function card(level,title,summary,why,accounts,credit){return {level,title,summary,why,accounts,credit}}
  function analyze(d,f){const i=2,p=1,out=[];
   const A=v(d,'activo',i),P=v(d,'pasivo',i),PN=v(d,'patrimonio',i);
   if(h(A)&&h(P)&&h(PN)){const dif=A-P-PN,lim=Math.max(Math.abs(A),1)*.005;if(Math.abs(dif)>lim)out.push(card('ALERTA','Balance: Activo no coincide con Pasivo + Patrimonio',`Existe una diferencia de G. ${money(dif)}.`,`Antes de evaluar solvencia hay que resolver la diferencia. Puede ser un error de carga, signo, clasificación o una cuenta faltante.`,'Total Activo; Total Pasivo; Patrimonio Neto.','No aumentar exposición hasta aclarar la diferencia.'))}
   const ventas=v(d,'ventas',i),ventas0=v(d,'ventas',p),costo=v(d,'costo',i),costo0=v(d,'costo',p),inv=v(d,'inventario',i),inv0=v(d,'inventario',p),cli=v(d,'clientes',i),cli0=v(d,'clientes',p),prov=v(d,'proveedores',i),prov0=v(d,'proveedores',p),caja=v(d,'caja',i),caja0=v(d,'caja',p),deuda=(v(d,'deudaCp',i)||0)+(v(d,'deudaLp',i)||0),deuda0=(v(d,'deudaCp',p)||0)+(v(d,'deudaLp',p)||0),inter=v(d,'intereses',i),res=v(d,'resultado',i),res0=v(d,'resultado',p);
   // Rentabilidad y ventas
   if(h(ventas)&&h(costo)&&ventas!==0){const m=(ventas-costo)/ventas,m0=h(ventas0)&&h(costo0)&&ventas0!==0?(ventas0-costo0)/ventas0:null;if(m0!=null&&m<m0-.05)out.push(card('ATENCION','Margen bruto: deterioro relevante',`El margen bruto pasó de ${pct(m0)} a ${pct(m)}.`,`La empresa necesita más ventas para generar el mismo margen. Una caída sostenida puede reducir capacidad de pago aunque las ventas aumenten.`,'Ventas; Costo de ventas; Resultado bruto.','Evaluar con mayor prudencia la línea si el deterioro continúa.'))}
   if(h(ventas)&&h(ventas0)&&ventas0!==0){const gv=(ventas-ventas0)/Math.abs(ventas0);if(gv<-.15)out.push(card('ATENCION','Ventas: caída significativa',`Las ventas disminuyeron ${pct(Math.abs(gv))} respecto del ejercicio anterior.`,`Una caída importante de actividad puede afectar generación de fondos y capacidad de pago.`,'Ventas 2024/2025; IVA si está disponible; resultado operativo.','No aumentar la línea sin considerar la caída de actividad.'))}
   // Clientes
   if(h(cli)&&h(ventas)&&ventas!==0){const days=cli/ventas*365,prev=h(cli0)&&h(ventas0)&&ventas0!==0?cli0/ventas0*365:null;if(days>90||prev!=null&&days>prev*1.5&&days>45)out.push(card('ATENCION','Clientes: aumento de plazo implícito',`El saldo equivale aproximadamente a ${days.toFixed(1)} días de ventas${prev!=null?`, frente a ${prev.toFixed(1)} días anteriores`:''}.`,`El crédito otorgado a clientes está absorbiendo más fondos. Puede deberse a mayores plazos o acumulación de saldos.`,'Clientes; Ventas; IVA mensual; Flujo: cobros de clientes.','Si afecta materialmente el crédito, pedir detalle de deuda de clientes; no hacerlo si la señal no es relevante.'))}
   // Inventario
   if(h(inv)&&h(cost)&&cost!==0){const turn=cost/inv,prev=h(inv0)&&h(costo0)&&costo0!==0?costo0/inv0:null;if(turn<1.5||prev!=null&&turn<prev*.6)out.push(card('ATENCION','Inventario: posible acumulación',`La rotación aproximada es ${turn.toFixed(2)} veces${prev!=null?`, frente a ${prev.toFixed(2)} veces anteriores`:''}.`,`El inventario puede estar absorbiendo capital más rápido que la actividad. No implica obsolescencia automáticamente.`,'Inventarios; Costo de ventas; Ventas; Proveedores; Caja.','Revisar antes de aumentar exposición; pedir detalle de inventario solo si es material.'))}
   // Proveedores / pasivos
   if(h(costo)&&h(inv)&&h(inv0)&&h(prov)&&h(prov0)){const compras=costo+inv-inv0,dprov=prov-prov0;if(compras>0&&dprov<0&&Math.abs(dprov)>compras*.25)out.push(card('ATENCION','Proveedores: compras altas con reducción de deuda',`Las compras reconstruidas son G. ${money(compras)} y los proveedores disminuyeron G. ${money(Math.abs(dprov))}.`,`Puede ser una cancelación real, compras al contado o una obligación registrada en otra cuenta. El movimiento necesita explicación.`,'Proveedores; Acreedores; Compras reconstruidas; Caja; Deuda financiera.','Si no se explica con los estados, solicitar detalle de deuda con proveedores.'))}
   // Posible omisión de pasivos
   const pasivo=v(d,'pasivo',i),pasivo0=v(d,'pasivo',p);if(h(pasivo)&&h(pasivo0)&&h(ventas)&&h(ventas0)&&ventas0!==0){const rp=pasivo/ventas,rp0=pasivo0/ventas0,gv=(ventas-ventas0)/Math.abs(ventas0),gp=(pasivo-pasivo0)/Math.max(Math.abs(pasivo0),1);if(gv>.15&&gp<-.15&&rp<rp0*.7)out.push(card('ALERTA','Posible subregistro u omisión de pasivos',`Las ventas aumentaron ${pct(gv)} mientras el pasivo disminuyó ${pct(Math.abs(gp))} y el pasivo/ventas cayó de ${pct(rp0)} a ${pct(rp)}.`,`El nivel de obligaciones registrado no acompaña el crecimiento de la actividad. Puede explicarse por cancelaciones reales, compras al contado o reclasificaciones, pero la señal justifica verificar si existe deuda no identificada.`,'Proveedores; Acreedores; Impuestos por pagar; Deuda financiera CP/LP; Flujo de pagos.','No concluir “pasivo omitido”. Si el flujo no explica la reducción, pedir detalle de deuda con proveedores y referencias bancarias.'))}
   // Deuda e intereses
   if(h(inter)&&h(deuda)){if(deuda===0&&inter!==0)out.push(card('ALERTA','Intereses registrados sin deuda al cierre',`Se registran intereses por G. ${money(inter)} y la deuda financiera al cierre es cero.`,`Puede existir deuda cancelada durante el año, devengamientos de períodos anteriores u otra obligación financiera que no queda visible al cierre.`,'Deuda financiera CP/LP; Intereses; Flujo de nuevas y cancelaciones de deuda.','Si no se explica con los movimientos, solicitar detalle de deuda o referencia bancaria.'));else if(deuda>0){const tasa=inter/((deuda+deuda0)/2);if(tasa>.25)out.push(card('ATENCION','Costo financiero elevado respecto de la deuda',`La relación aproximada entre intereses y deuda media es ${pct(tasa)}.`,`Puede reflejar tasas altas, deuda de corto plazo, refinanciaciones o intereses extraordinarios. No es una tasa contractual.`,'Deuda CP/LP; Intereses; nuevas deudas; pagos de deuda.','Revisar deuda antes de ampliar exposición.'))}}
   // Resultado vs caja
   if(h(res)&&h(caja)&&h(caja0)&&res>0&&caja<caja0){const ca=(caja0-caja)/Math.max(res,1);if(ca>.5)out.push(card('ATENCION','Resultado positivo con caída de caja',`El resultado es positivo, pero Caja/Bancos disminuyó G. ${money(caja0-caja)}.`,`El resultado contable no se convirtió en efectivo en la misma medida. Puede explicarse por inversiones, aumento de clientes/inventarios o cancelación de deuda; si no se explica, existe presión de liquidez.`,'Caja; Clientes; Inventarios; Deuda; Flujo de fondos.','Revisar el flujo antes de aumentar la línea; no pedir documentos adicionales automáticamente.'))}
   // Patrimonio
   if(h(PN)&&h(res)&&h(v(d,'patrimonio',p))){const p0=v(d,'patrimonio',p),delta=PN-p0;if(Math.abs(delta-res)>Math.max(Math.abs(res)*.15,1)&&Math.abs(delta)>Math.max(Math.abs(PN)*.05,1))out.push(card('ATENCION','Patrimonio: evolución no explicada por el resultado',`El patrimonio cambió G. ${money(delta)} mientras el resultado del ejercicio fue G. ${money(res)}.`,`La diferencia puede corresponder a aportes, retiros, dividendos, reservas o ajustes. Si no existe una explicación, la evolución patrimonial no queda clara.`,'Patrimonio Neto; Resultado; Capital; Reservas; Resultados acumulados.','Verificar movimientos patrimoniales antes de usar el patrimonio como respaldo crediticio.'))}
   // Caja/flujo exacto si disponible
   const flow=v(f,'varCaja',i);if(h(flow)&&h(caja)&&h(caja0)){const dif=(caja-caja0)-flow;if(Math.abs(dif)>1)out.push(card('ALERTA','Flujo de fondos no concilia con Caja/Bancos',`La variación de Caja/Bancos es G. ${money(caja-caja0)} y el flujo informa G. ${money(flow)}. Diferencia: G. ${money(dif)}.`,`Es una diferencia directa entre dos estados. Puede existir una clasificación incorrecta, saldo inicial/final incorrecto o movimiento omitido.`,'Caja/Bancos inicial y final; Variación neta de caja; detalle del flujo.','Aclarar la diferencia antes de tomar una decisión crediticia basada en la liquidez.'))}
   return out;
  }
  function grade(a){const al=a.filter(x=>x.level==='ALERTA').length,at=a.filter(x=>x.level==='ATENCION').length;if(al>=2)return['ALTO RIESGO','g-bad'];if(al===1)return['RIESGO A REVISAR','g-warn'];if(at>=3)return['PRECAUCIÓN','g-warn'];if(at>0)return['FAVORABLE CON OBSERVACIONES','g-good'];return['FAVORABLE','g-excellent']}
  function render(rows){if(!rows)return;const d=extract(rows,aliases),f=extract(rows,flujo),a=analyze(d,f),g=grade(a),audit=$('auditoria');if(!audit)return;const old=$('motorFinanciero');if(old)old.remove();const s=document.createElement('section');s.id='motorFinanciero';s.className='card';let html=`<h2>CONTROLES FINANCIEROS — ANÁLISIS CREDITICIO</h2><div class="body"><div class="diag-grade ${g[1]}"><div class="diag-label">CONCLUSIÓN DEL PERÍODO ACTUAL</div><div class="diag-value">${esc(g[0])}</div><div>${a.length?`Se detectaron ${a.length} situación(es) que requieren atención entre las relaciones financieras analizadas.`:'No se detectaron anomalías relevantes con los controles disponibles.'}</div><div class="note">El período actual determina la conclusión. Los períodos anteriores se utilizan para comparar evolución y detectar cambios anormales.</div></div>`;
   if(a.length){html+='<h3>ANOMALÍAS DETECTADAS</h3><div class="diag-list">';a.forEach((x,i)=>html+=`<article class="diag-item actionable"><div class="diag-head"><div><span class="diag-num">${i+1}</span><b>${esc(x.title)}</b></div><span class="priority p-${x.level.toLowerCase()}">${x.level}</span></div><p><b>Qué detectó:</b> ${esc(x.summary)}</p><p><b>Qué significa:</b> ${esc(x.why)}</p><p><b>Cuentas a relacionar:</b> ${esc(x.accounts)}</p><p><b>Impacto crediticio:</b> ${esc(x.credit)}</p></article>`).join('');html+='</div>'}else html+='<div class="diag-ok"><b>NO SE DETECTARON ANOMALÍAS RELEVANTES.</b><br>Esto no significa que la empresa sea de bajo riesgo en términos absolutos; significa que estos controles no encontraron una señal relevante con la información disponible.</div>';
   html+='<details class="technical"><summary>Ver fórmulas y controles utilizados</summary><div class="diag-policy"><b>Controles:</b> ecuación patrimonial; crecimiento de ventas; margen bruto; clientes/ventas; inventarios/costo; proveedores/compras reconstruidas; posible subregistro de pasivos; deuda/intereses; resultado/caja; evolución patrimonial; caja/flujo.</div></details></div></section>';s.innerHTML=html;audit.insertBefore(s,audit.firstChild)}
  function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>read().then(render),3000));}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
