/* MOTOR CREDITICIO V4 — análisis financiero integral del período actual.
   2025 determina la conclusión; 2023-2024 solo sirven para tendencia.
   No genera alertas por movimientos conciliados y no repite controles de obligaciones.
*/
(function(){
  const $=id=>document.getElementById(id);
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const num=v=>{if(v==null||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');const n=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(n)?n:null};
  const money=n=>n==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(n);
  const pct=n=>n==null||!Number.isFinite(n)?'—':(n*100).toFixed(1)+'%';
  const spct=n=>n==null||!Number.isFinite(n)?'—':(n>=0?'+':'')+(n*100).toFixed(1)+'%';
  const ratio=n=>n==null||!Number.isFinite(n)?'—':n.toFixed(2)+'x';
  const days=n=>n==null||!Number.isFinite(n)?'—':n.toFixed(1)+' días';
  const growth=(a,b)=>a==null||b==null||b===0?null:(a-b)/Math.abs(b);
  const abs=n=>n==null?null:Math.abs(n);
  const aliases={
    cash:['disponible (caja y bancos)','disponible caja y bancos','caja y bancos','disponible'],invFinCP:['colocaciones e inversiones financieras - cp'],clients:['creditos comerciales - cp (clientes)','creditos comerciales cp (clientes)'],inventory:['inventario'],advProv:['anticipos a proveedores'],currentAssets:['total activo corriente'],totalAssets:['total activo'],finDebtCP:['deudas financieras - cp','deudas financieras cp'],partnerDebtCP:['deudas con socios y otras cooperativas - cp'],suppliersCP:['deudas comerciales - cp (proveedores)','deudas comerciales cp (proveedores)'],advancesClients:['anticipos de clientes'],provisions:['provisiones'],creditors:['acreedores varios'],currentLiab:['total pasivo corriente'],finDebtLP:['deudas financieras - lp','deudas financieras lp'],partnerDebtLP:['deudas con socios y otras cooperativas - lp'],suppliersLP:['deudas comerciales - lp (proveedores)','deudas comerciales lp'],totalLiab:['total pasivo'],equity:['total patrimonio neto'],sales:['ventas netas'],cost:['costo de ventas'],gross:['resultado bruto comercial principal','resultado bruto total'],ebitda:['ebitda (flujo operativo puro/caja real)'],ebit:['ebit (resultado operativo) (utilidad op contable)'],interestPaid:['intereses financieros pagados'],netResult:['resultado neto total del ejercicio','resultado neto','resultado del ejercicio'],flowClients:['variacion cuentas a cobrar comerciales cp','variacion cuentas a cobrar comerciales'],flowInventory:['variacion inventario + anticipos a proveedores'],flowSuppliers:['variacion cuentas a pagar comerciales cp'],flowOp:['generacion (aplicacion) neta operativa','generaciones operativas'],flowDebtPayCP:['pago deudas financieras cp'],flowDebtPayLP:['pago deudas financieras lp'],flowCommercialPayLP:['pago deudas comerciales lp'],flowNewDebtCP:['nuevas deudas financieras cp'],flowNewDebtLP:['nuevas deudas financieras lp'],flowNewCommercialLP:['nuevas deudas comerciales lp'],flowCash:['variacion neta de caja']
  };
  function findRow(rows,names){const a=names.map(norm);for(let r=0;r<rows.length;r++){const s=norm(rows[r]?.[1]??rows[r]?.[0]);if(a.includes(s))return r}for(let r=0;r<rows.length;r++){const s=norm(rows[r]?.[1]??rows[r]?.[0]);if(a.some(x=>s===x||s.startsWith(x+' ')||s.includes(x)))return r}return -1}
  function read(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return Promise.resolve(null);return f.arrayBuffer().then(b=>{const wb=XLSX.read(b,{type:'array',raw:true,blankrows:true});const sh=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json(wb.Sheets[sh],{header:1,defval:null,raw:true,blankrows:true});const cols=[2,5,8];const year=v=>{const m=String(v??'').match(/(?:19|20)\d{2}/);return m?m[0]:null};let years=cols.map(c=>year(rows[4]?.[c]));if(years.some(x=>!x)){for(let r=0;r<12;r++){const y=cols.map(c=>year(rows[r]?.[c]));if(y.every(Boolean)){years=y;break}}}const d={years,rows,name:sh};for(const[k,a]of Object.entries(aliases)){const r=findRow(rows,a);d[k]=r<0?null:cols.map(c=>num(rows[r]?.[c]))}return d})}
  const v=(d,k,i)=>d[k]?.[i]??null;
  function analyze(d){
    const years=d.years||[],i=years.length-1,p=Math.max(0,i-1),cur=years[i]||'ACTUAL',prev=years[p]||'ANTERIOR',f=[],info=[];
    const add=(level,title,detected,meaning,accounts,action)=>f.push({level,title,detected,meaning,accounts,action});
    const note=(label,value,kind='normal')=>info.push({label,value,kind});
    const cash=v(d,'cash',i),cashP=v(d,'cash',p),invFin=v(d,'invFinCP',i),clients=v(d,'clients',i),clientsP=v(d,'clients',p),inventory=v(d,'inventory',i),inventoryP=v(d,'inventory',p),ca=v(d,'currentAssets',i),cl=v(d,'currentLiab',i),ta=v(d,'totalAssets',i),tl=v(d,'totalLiab',i),eq=v(d,'equity',i),debtCP=v(d,'finDebtCP',i)||0,debtLP=v(d,'finDebtLP',i)||0,finDebt=debtCP+debtLP,suppliers=v(d,'suppliersCP',i)||0,suppliersLP=v(d,'suppliersLP',i)||0,sales=v(d,'sales',i),salesP=v(d,'sales',p),cost=v(d,'cost',i),costP=v(d,'cost',p),gross=v(d,'gross',i),ebitda=v(d,'ebitda',i),ebit=v(d,'ebit',i),interest=v(d,'interestPaid',i),net=v(d,'netResult',i),netP=v(d,'netResult',p),op=v(d,'flowOp',i),flowCash=v(d,'flowCash',i),flowClients=v(d,'flowClients',i),flowInv=v(d,'flowInventory',i),flowSup=v(d,'flowSuppliers',i),newFin=(v(d,'flowNewDebtCP',i)||0)+(v(d,'flowNewDebtLP',i)||0),payFin=Math.abs(v(d,'flowDebtPayCP',i)||0)+Math.abs(v(d,'flowDebtPayLP',i)||0),newComm=v(d,'flowNewCommercialLP',i)||0,payComm=Math.abs(v(d,'flowCommercialPayLP',i)||0);
    const delta=(a,b)=>a!=null&&b!=null?a-b:null,cashDelta=delta(cash,cashP),clientDelta=delta(clients,clientsP),invDelta=delta(inventory,inventoryP),supDelta=delta(suppliers,v(d,'suppliersCP',p)),sg=growth(sales,salesP),ng=growth(net,netP),cg=growth(clients,clientsP),ig=growth(inventory,inventoryP),tg=growth(tl,v(d,'totalLiab',p));
    const currentRatio=ca!=null&&cl>0?ca/cl:null,quickRatio=cl>0?((cash||0)+(invFin||0)+(clients||0))/cl:null,workingCapital=ca!=null&&cl!=null?ca-cl:null,debtAsset=ta>0?tl/ta:null,finDebtAsset=ta>0?finDebt/ta:null,leverage=eq!=null&&eq!==0?tl/Math.abs(eq):null,grossMargin=sales>0&&gross!=null?gross/sales:null,ebitdaMargin=sales>0&&ebitda!=null?ebitda/sales:null,netMargin=sales>0&&net!=null?net/sales:null,interestCoverage=interest!=null&&Math.abs(interest)>0&&ebitda!=null?ebitda/Math.abs(interest):null,debtEbitda=ebitda!=null&&ebitda>0?finDebt/ebitda:null,receivableDays=sales>0&&clients!=null?clients/sales*365:null,inventoryDays=cost>0&&inventory!=null?inventory/cost*365:null,supplierDays=cost>0&&suppliers!=null?suppliers/cost*365:null,cashFlowDeltaOk=flowCash!=null&&cashDelta!=null&&Math.abs(flowCash-cashDelta)<=Math.max(1,Math.abs(cashDelta)*0.000001);
    note('Liquidez corriente',ratio(currentRatio),currentRatio!=null&&currentRatio<1?'bad':currentRatio!=null&&currentRatio<1.2?'warn':'good');note('Liquidez rápida',ratio(quickRatio),quickRatio!=null&&quickRatio<0.8?'bad':quickRatio!=null&&quickRatio<1?'warn':'good');note('Capital de trabajo',money(workingCapital));note('Endeudamiento total',pct(debtAsset),debtAsset!=null&&debtAsset>.75?'bad':debtAsset!=null&&debtAsset>.60?'warn':'good');note('Deuda financiera / activo',pct(finDebtAsset));note('Margen neto',pct(netMargin),netMargin!=null&&netMargin<0?'bad':netMargin!=null&&netMargin<.03?'warn':'good');note('Cobertura de intereses',ratio(interestCoverage),interestCoverage!=null&&interestCoverage<1?'bad':interestCoverage!=null&&interestCoverage<2?'warn':'good');note('Días de clientes',days(receivableDays),receivableDays!=null&&receivableDays>90?'bad':receivableDays!=null&&receivableDays>60?'warn':'good');note('Días de inventario',days(inventoryDays),inventoryDays!=null&&inventoryDays>180?'bad':inventoryDays!=null&&inventoryDays>90?'warn':'good');note('Días de proveedores',days(supplierDays));note('Flujo operativo',money(op),op!=null&&op<0?'bad':'good');note('Flujo neto de caja',money(flowCash),flowCash!=null&&flowCash<0?'warn':'good');
    if(sg!=null&&sg<=-.15)add(sg<=-.30?'ALTA':'MEDIA','Ventas: deterioro de actividad',`Ventas ${prev}: G. ${money(salesP)} → ${cur}: G. ${money(sales)} (${spct(sg)}). Resultado neto ${net!=null?spct(ng):'no disponible'}; flujo operativo ${op!=null?'G. '+money(op):'no disponible'}.`,`Una caída relevante de ventas reduce la capacidad de generar margen y caja. Se vuelve crítica cuando el resultado o el flujo operativo también se deterioran.`,`Ventas ↔ Resultado neto ↔ EBITDA/EBIT ↔ Flujo operativo ↔ Caja`,`Contrastar la tendencia con IVA cuando esté disponible. Si los estados y el flujo ya explican el deterioro, no pedir documentación adicional.`);
    if(net!=null&&net<0)add(Math.abs(net)>Math.max(1,(sales||0)*.05)?'ALTA':'MEDIA','Resultado neto negativo',`Resultado neto ${cur}: G. ${money(net)}${netP!=null?`; anterior: G. ${money(netP)}.`:''}`,`El ejercicio no genera utilidad contable suficiente para absorber riesgos adicionales. Debe analizarse junto con flujo operativo, caja y estructura de deuda.`,`Resultado neto ↔ Ventas ↔ EBITDA/EBIT ↔ Flujo operativo ↔ Caja`,`Revisar si la pérdida es recurrente u originada por un hecho puntual. Si compromete caja o cobertura, considerar reducción de exposición.`);
    if(ebitda!=null&&sales>0&&ebitda<0)add('ALTA','EBITDA negativo',`EBITDA G. ${money(ebitda)} sobre ventas G. ${money(sales)} (${pct(ebitdaMargin)}).`,`La operación principal no está generando caja operativa antes de intereses e impuestos.`,`Ventas ↔ Costo ↔ Gastos operativos ↔ EBITDA ↔ Flujo operativo`,`Comprobar si el déficit es puntual y si existe fuente de fondos para sostener la operación.`);
    if(currentRatio!=null&&currentRatio<1)add(currentRatio<.75?'ALTA':'MEDIA','Liquidez corriente insuficiente',`Activo corriente G. ${money(ca)} frente a pasivo corriente G. ${money(cl)}; razón corriente ${ratio(currentRatio)}.`,`Los activos realizables en el corto plazo no cubren las obligaciones corrientes.`,`Activo corriente ↔ Pasivo corriente ↔ Caja ↔ Clientes ↔ Inventario ↔ Flujo operativo`,`Revisar vencimientos y fuentes de caja antes de ampliar exposición.`);else if(currentRatio!=null&&currentRatio<1.2)add('MEDIA','Liquidez corriente ajustada',`Activo corriente G. ${money(ca)}; pasivo corriente G. ${money(cl)}; razón corriente ${ratio(currentRatio)}.`,`Existe poco margen para absorber atrasos de cobros, compras de inventario o vencimientos.`,`Activo corriente ↔ Pasivo corriente ↔ Caja ↔ Clientes ↔ Inventario`,`Revisar la composición del activo corriente antes de ampliar exposición.`);
    if(quickRatio!=null&&quickRatio<1)add(quickRatio<.7?'ALTA':'MEDIA','Liquidez rápida débil',`Caja + inversiones CP + clientes G. ${money((cash||0)+(invFin||0)+(clients||0))} frente a pasivo corriente G. ${money(cl)}; razón rápida ${ratio(quickRatio)}.`,`Sin vender inventario, la cobertura de obligaciones corrientes es insuficiente o ajustada.`,`Caja ↔ Inversiones CP ↔ Clientes ↔ Pasivo corriente`,`Priorizar fuentes de caja y vencimientos.`);
    if(receivableDays!=null&&(receivableDays>90||(clientsP!=null&&salesP>0&&receivableDays>clientsP/salesP*365+30))){const match=flowClients!=null&&clientDelta!=null&&Math.abs(flowClients-clientDelta)<=Math.max(1,Math.abs(clientDelta)*.000001);add(receivableDays>120?'ALTA':'MEDIA','Clientes: aumento del plazo de cobro',`Clientes G. ${money(clients)}; ventas G. ${money(sales)}; equivalente a ${days(receivableDays)}. ${clientsP!=null&&salesP>0?`Anterior: ${days(clientsP/salesP*365)}. `:''}${clientDelta!=null?`Aumento de saldo G. ${money(clientDelta)}.`:''}`,match?'El aumento está explicado por el movimiento del Flujo de cuentas a cobrar. Es una señal de mayor plazo, no una inconsistencia.':'El saldo requiere contraste con el Flujo para determinar cuánto de la venta quedó pendiente de cobro.','Clientes ↔ Ventas ↔ Flujo de cuentas a cobrar ↔ Caja',match?'Primero comprobar el Flujo. Si concilia, no pedir documentación; si queda diferencia material, revisar detalle de cuentas por cobrar.':'Primero comprobar el Flujo y solo después pedir detalle si persiste una diferencia material.');}
    if(inventory!=null&&cost>0&&(inventoryDays>180||(inventoryP!=null&&costP>0&&inventoryDays>inventoryP/costP*365+45)))add((sg!=null&&sg<0)?'ALTA':'MEDIA','Inventario: posible acumulación',`Inventario G. ${money(inventory)}; costo G. ${money(cost)}; equivalente a ${days(inventoryDays)}. ${inventoryP!=null&&costP>0?`Anterior: ${days(inventoryP/costP*365)}.`:''}`,`El inventario inmoviliza capital. Si las ventas caen, aumenta el riesgo de recuperación lenta del capital invertido.`,'Inventario ↔ Costo de ventas ↔ Ventas ↔ Caja ↔ Flujo operativo','Comprobar rotación y tendencia. Pedir detalle solo si estados e información tributaria no permiten explicar el nivel.');
    if(debtAsset!=null&&debtAsset>.75)add('ALTA','Endeudamiento total elevado',`Pasivo total G. ${money(tl)}/Activo total G. ${money(ta)} = ${pct(debtAsset)}.`,`Una proporción elevada de activos financiada con terceros reduce el colchón patrimonial ante pérdidas o caídas de actividad.`,'Activo total ↔ Pasivo total ↔ Patrimonio ↔ Deuda financiera','Evaluar capacidad de pago y calidad del patrimonio antes de ampliar exposición.');else if(debtAsset!=null&&debtAsset>.60)add('MEDIA','Endeudamiento total relevante',`Pasivo total G. ${money(tl)} sobre activo total G. ${money(ta)} = ${pct(debtAsset)}.`,`La estructura tiene una dependencia relevante de terceros y debe sostenerse con flujo suficiente.`,'Activo total ↔ Pasivo total ↔ Patrimonio','Cruzar con EBITDA, flujo operativo y vencimientos.');
    if(leverage!=null&&leverage>3)add('ALTA','Apalancamiento patrimonial elevado',`Pasivo total G. ${money(tl)} frente a patrimonio neto G. ${money(eq)} = ${ratio(leverage)}.`,`La deuda de terceros supera ampliamente el respaldo patrimonial.`,'Pasivo ↔ Patrimonio ↔ Resultado ↔ Flujo operativo','Evaluar margen de seguridad patrimonial y capacidad de servicio de deuda.');
    if(finDebt>0&&interestCoverage!=null&&interestCoverage<1)add('ALTA','Cobertura de intereses insuficiente',`EBITDA G. ${money(ebitda)}; intereses pagados G. ${money(interest)}; cobertura ${ratio(interestCoverage)}.`,`La generación operativa no alcanza para cubrir los intereses del período.`,'EBITDA ↔ Intereses ↔ Deuda financiera ↔ Flujo operativo','No ampliar exposición sin comprobar fuente de fondos y estructura de vencimientos.');else if(finDebt>0&&interestCoverage!=null&&interestCoverage<2)add('MEDIA','Cobertura de intereses ajustada',`EBITDA G. ${money(ebitda)}; intereses G. ${money(interest)}; cobertura ${ratio(interestCoverage)}.`,`Existe poco margen operativo para absorber aumentos de intereses o una caída de actividad.`,'EBITDA ↔ Intereses ↔ Deuda financiera','Revisar sensibilidad de la capacidad de pago.');
    if(debtEbitda!=null&&debtEbitda>4)add('ALTA','Deuda financiera elevada respecto de EBITDA',`Deuda financiera G. ${money(finDebt)} / EBITDA G. ${money(ebitda)} = ${ratio(debtEbitda)}.`,`La deuda financiera requiere varios períodos de generación operativa para ser cubierta.`,'Deuda financiera CP/LP ↔ EBITDA ↔ Flujo operativo','Revisar amortizaciones y refinanciaciones antes de aumentar exposición.');
    if(interest!=null&&Math.abs(interest)>0&&finDebt===0)add((newFin>0||payFin>0)?'MEDIA':'ALTA','Intereses sin deuda financiera al cierre',`Intereses pagados G. ${money(interest)} y deuda financiera al cierre G. 0. Flujo: nuevas G. ${money(newFin)}; pagos G. ${money(payFin)}.`,(newFin>0||payFin>0)?'La deuda pudo existir y haberse cancelado durante el período. No es necesariamente inconsistencia.':'El estado muestra gasto financiero sin saldo de deuda ni movimientos de deuda identificables. Puede corresponder a deuda cancelada, períodos anteriores, refinanciación o clasificación en otra cuenta.','Intereses ↔ Deuda financiera CP/LP ↔ Nuevas deudas ↔ Pagos','Si nuevas deudas/pagos explican el cierre en cero, no pedir documentación. Si no cierran, revisar detalle de deuda y referencias bancarias.');
    if(op!=null&&op<0)add(op<-(sales||0)*.05?'ALTA':'MEDIA','Flujo operativo negativo',`Generación neta operativa: G. ${money(op)}.`,`La actividad principal consume caja en lugar de generarla. Es una señal directa de presión sobre la capacidad de pago.`,'Resultado ↔ Clientes ↔ Inventario ↔ Proveedores ↔ Flujo operativo ↔ Caja','Identificar si el déficit es puntual o recurrente.');
    if(cash!=null&&cashP!=null&&cash<cashP){const drop=cashP-cash;if(flowCash!=null&&!cashFlowDeltaOk)add('MEDIA','Caja disminuye sin conciliación con el Flujo',`Caja G. ${money(cashP)} → G. ${money(cash)}; variación G. ${money(-drop)}; Flujo de caja reportado G. ${money(flowCash)}.`,`La variación de caja no coincide con la variación neta informada por el Flujo. Esto sí requiere revisión del puente de efectivo.`,'Caja ↔ Variación neta de caja ↔ Flujo operativo ↔ Flujo financiero ↔ Flujo no operativo','Revisar primero el puente de caja. Solo si la diferencia permanece, solicitar explicación específica.');else if(net!=null&&net>0)add('MEDIA','Resultado positivo pero caja se debilita',`Resultado neto G. ${money(net)}; Caja G. ${money(cashP)} → G. ${money(cash)}; disminución G. ${money(drop)}.${clientDelta>0?` Clientes +G. ${money(clientDelta)}.`:''}${invDelta>0?` Inventario +G. ${money(invDelta)}.`:''}`,`La utilidad no se transformó completamente en efectivo. El capital puede estar absorbido por cuentas por cobrar, inventarios u otras aplicaciones.`,'Resultado ↔ Clientes ↔ Inventario ↔ Proveedores ↔ Deuda ↔ Flujo ↔ Caja','Si el Flujo concilia la disminución de caja, no pedir documentación adicional.');}
    if(op!=null&&cash!=null&&cashP!=null&&op<0&&cash<cashP)add('ALTA','Operación consume caja y el efectivo cae',`Flujo operativo G. ${money(op)} y Caja disminuye G. ${money(cashP-cash)}.`,`La actividad consume efectivo y el colchón de caja se reduce.`,`Flujo operativo ↔ Caja ↔ Clientes ↔ Inventario ↔ Proveedores`,`Considerar reducción de exposición o revisión de vencimientos si el patrón no es puntual.`);
    if(cost!=null&&inventory!=null&&inventoryP!=null&&suppliers!=null&&v(d,'suppliersCP',p)!=null){const purchases=cost+invDelta;if(purchases>0&&supDelta<0&&Math.abs(supDelta)>purchases*.20){const flowExplains=flowSup!=null&&Math.abs(flowSup+supDelta)<=Math.max(1,Math.abs(supDelta)*.000001);add('MEDIA','Proveedores: compras financiadas y pagos a comprobar',`Compras reconstruidas G. ${money(purchases)}; Proveedores G. ${money(v(d,'suppliersCP',p))} → G. ${money(suppliers)} (${spct(growth(suppliers,v(d,'suppliersCP',p)))}).`,flowExplains?'La reducción del saldo está reflejada por el Flujo de cuentas a pagar. No constituye por sí sola una inconsistencia.':'Las compras estimadas no quedan suficientemente explicadas por la variación de proveedores; pueden haber sido pagadas al contado o mediante otra fuente.','Costo de ventas ↔ Inventario ↔ Proveedores ↔ Caja ↔ Flujo','Primero comprobar Caja/Flujo. Si concilia, no pedir documentación; si no, revisar detalle de proveedores.');}}
    const provNow=(suppliers||0)+(suppliersLP||0),provPrev=(v(d,'suppliersCP',p)||0)+(v(d,'suppliersLP',p)||0),otherNow=(v(d,'creditors',i)||0)+(v(d,'advancesClients',i)||0)+(v(d,'provisions',i)||0)+finDebt+(v(d,'partnerDebtCP',i)||0)+(v(d,'partnerDebtLP',i)||0)+provNow,otherPrev=(v(d,'creditors',p)||0)+(v(d,'advancesClients',p)||0)+(v(d,'provisions',p)||0)+(v(d,'finDebtCP',p)||0)+(v(d,'finDebtLP',p)||0)+(v(d,'partnerDebtCP',p)||0)+(v(d,'partnerDebtLP',p)||0)+provPrev;
    if(tg!=null&&tg<=-.20&&sg!=null&&sg>-.05&&otherPrev>0&&otherNow<otherPrev*.80&&op!=null&&op<0)add('ALTA','Pasivos: posible reducción no explicada',`Pasivo total ${spct(tg)} mientras ventas ${spct(sg)}; obligaciones identificadas también disminuyen y el flujo operativo es negativo.`,`No demuestra pasivo omitido. Es una señal cruzada porque la actividad no cayó en igual proporción, las obligaciones visibles bajaron y la operación no genera caja.`,'Pasivo ↔ Proveedores ↔ Acreedores ↔ Deuda ↔ Flujo operativo ↔ Ventas','Comprobar primero pagos, refinanciaciones y reclasificaciones. Solo si el puente no explica la reducción, pedir detalle de obligaciones y referencias.');
    if(newComm!==0||payComm!==0){const balNow=v(d,'suppliersLP',i),balPrev=v(d,'suppliersLP',p),balDelta=delta(balNow,balPrev),expected=newComm-payComm,tol=Math.max(1,Math.max(abs(expected)||0,abs(balDelta)||0)*.000001);if(!(balNow!=null&&balPrev!=null&&Math.abs((balDelta||0)-expected)<=tol))add('MEDIA','Nueva deuda comercial LP: conciliación pendiente',`Flujo: nuevas G. ${money(newComm)}; pagos G. ${money(payComm)}. Balance: Deudas Comerciales LP G. ${money(balPrev)} → G. ${money(balNow)}; variación G. ${money(balDelta)}.`,`La nueva deuda y los pagos identificables no explican por sí solos el cambio del saldo de largo plazo. Puede existir vencimiento, reclasificación u otro movimiento.`,'Nuevas deudas comerciales LP ↔ Pagos de deuda comercial LP ↔ Deudas Comerciales LP ↔ Flujo','Revisar vencimientos y reclasificaciones. Solo si permanece una diferencia material, pedir detalle de deuda con proveedores.');}
    const critical=[['Ventas',sales],['Activo corriente',ca],['Pasivo corriente',cl],['Activo total',ta],['Pasivo total',tl],['Patrimonio',eq],['Resultado neto',net],['Flujo operativo',op],['Caja/Bancos',cash]].filter(x=>x[1]==null).map(x=>x[0]);
    if(critical.length)add('MEDIA','Cobertura de datos incompleta',`No se identificaron automáticamente: ${critical.join(', ')}.`,`La ausencia de una cuenta no significa que el cliente tenga un problema; significa que el motor no debe concluir que el indicador es bueno o malo sin ese dato.`,'Estructura del Estado ↔ cuentas faltantes','Revisar la clasificación del Excel o ampliar los alias de lectura. No solicitar documentación solo por una etiqueta no reconocida.');
    const order={ALTA:0,MEDIA:1};f.sort((a,b)=>order[a.level]-order[b.level]);return {current:cur,prev,alerts:f,info,coverage:critical};
  }
  function grade(a){const hi=a.filter(x=>x.level==='ALTA').length,me=a.filter(x=>x.level==='MEDIA').length;if(hi>=3)return['MALO','Varias señales de riesgo afectan la capacidad de pago o la estructura financiera.','g-bad'];if(hi>=1)return['REGULAR','Existe al menos una señal relevante que debe comprobarse antes de una decisión de crédito.','g-warn'];if(me>=3)return['REGULAR','Hay varias señales actuales que requieren revisión, aunque no prueban por sí solas una inconsistencia.','g-warn'];if(me>=1)return['BIEN','Existe una o más señales puntuales, pero no se observa un deterioro crítico con la información disponible.','g-good'];return['EXCELENTE','No se detectan señales relevantes en el período actual con los datos identificados.','g-excellent'];}
  function render(r){const a=$('auditoria');if(!a)return;document.getElementById('diagnosticoV2')?.remove();const g=grade(r.alerts),sec=document.createElement('section');sec.id='diagnosticoV2';sec.className='card';const alerts=r.alerts.slice(0,8),groups=[['LIQUIDEZ',['Liquidez corriente','Liquidez rápida','Capital de trabajo']],['SOLVENCIA',['Endeudamiento total','Deuda financiera / activo']],['RENTABILIDAD',['Margen neto','Cobertura de intereses']],['GESTIÓN',['Días de clientes','Días de inventario','Días de proveedores']],['CAJA Y FLUJO',['Flujo operativo','Flujo neto de caja']]],ind=groups.map(gr=>`<div class="metric-group"><h4>${gr[0]}</h4>${r.info.filter(x=>gr[1].includes(x.label)).map(x=>`<div class="metric ${x.kind}"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}</div>`).join('');sec.innerHTML=`<h2>4. CONCLUSIÓN CREDITICIA — ${esc(r.current)}</h2><div class="body credit-v2"><div class="v2-grade ${g[2]}"><div class="v2-kicker">RESULTADO DEL PERÍODO ACTUAL</div><div class="v2-value">${esc(g[0])}</div><div class="v2-summary">${esc(g[1])}</div><div class="v2-rule"><b>Regla:</b> ${esc(r.current)} determina la conclusión. ${esc(r.prev)} y los períodos anteriores solo miden tendencia.</div></div><h3>LECTURA FINANCIERA DEL PERÍODO</h3><div class="metric-grid">${ind}</div>${alerts.length?`<h3>ALERTAS QUE CAMBIAN LA LECTURA DEL CRÉDITO</h3><div class="v2-alerts">${alerts.map((x,i)=>`<article class="v2-alert level-${x.level.toLowerCase()}"><div class="v2-head"><div><span class="v2-num">${i+1}</span><b>${esc(x.title)}</b></div><span class="v2-priority">${esc(x.level)}</span></div><div class="v2-row"><b>QUÉ DETECTÓ</b><span>${esc(x.detected)}</span></div><div class="v2-row"><b>QUÉ SIGNIFICA</b><span>${esc(x.meaning)}</span></div><div class="v2-row"><b>CUENTAS QUE RELACIONÓ</b><span>${esc(x.accounts)}</span></div><div class="v2-row action"><b>DECISIÓN</b><span>${esc(x.action)}</span></div></article>`).join('')}</div>`:`<div class="v2-clean"><b>NO HAY ALERTAS RELEVANTES EN ${esc(r.current)}.</b><br>Los indicadores anteriores muestran la lectura financiera que sustenta esta conclusión.</div>`}${r.coverage.length?`<div class="compact-note"><b>COBERTURA DEL MOTOR:</b> faltan o no fueron identificadas automáticamente estas cuentas: ${esc(r.coverage.join(', '))}. Esto limita el alcance de algunos indicadores, pero no se interpreta como riesgo del cliente.</div>`:''}<details class="v2-method"><summary>Ver cálculo técnico</summary><div>El motor cruza liquidez, solvencia, rentabilidad, gestión, deuda, intereses, caja y flujo. Una señal conciliada no se transforma en alerta. Los años anteriores se usan para medir tendencia, no para sustituir el resultado del período actual.</div></details></div>`;a.appendChild(sec);[...a.children].forEach(el=>{if(el.id!=='flujoCompacto'&&el.id!=='diagnosticoV2')el.style.display='none'});}
  function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>read().then(d=>{if(d)render(analyze(d))}),450));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();