/* AUDITORIA DE COHERENCIA FINANCIERA - MOTOR DE CONCILIACION PROFUNDA
   Lectura: todos los periodos para construir antecedentes; el ultimo periodo
   con informacion es el periodo actual. Los hallazgos se refieren al actual.
*/
window.MotorCoherenciaFinanciera=(()=>{
  const n=x=>x==null||x===''||!Number.isFinite(Number(x))?null:Number(x);
  const val=(d,k,y)=>d?.matched?.[k]?.values?.[y]??null;
  const pct=(a,b)=>n(a)!=null&&n(b)!=null&&n(b)!==0?(n(a)/n(b)-1)*100:null;
  const add=(a,t,nv,titulo,formula,valores,interpretacion,conclusion)=>a.push({tipo:t,nivel:nv,titulo,formula,valores,interpretacion,conclusion});
  const has=(...x)=>x.every(v=>n(v)!=null);
  const yearsOf=data=>[...new Set(Object.values(data||{}).filter(Boolean).flatMap(d=>d.periods||[]).map(String).filter(y=>/^\d{4}$/.test(y)))].sort();
  const previousOf=(data,actual)=>{const ys=yearsOf(data),i=ys.indexOf(actual);return i>0?ys[i-1]:null;};

  function integridad(data,a,actual){
    const b=data.balance,r=data.resultados;
    const activo=val(b,'total_activo',actual),ac=val(b,'total_activo_corriente',actual),anc=val(b,'total_activo_no_corriente',actual);
    const pasivo=val(b,'total_pasivo',actual),pc=val(b,'total_pasivo_corriente',actual),pnc=val(b,'total_pasivo_no_corriente',actual),pat=val(b,'total_patrimonio',actual);
    if(has(activo,pasivo,pat)){
      const d=activo-pasivo-pat;
      add(a,'inconsistencia',Math.abs(d)>1?'crit':'info','Ecuacion patrimonial '+(Math.abs(d)>1?'no ':'')+'conciliada — '+actual,'Activo − Pasivo − Patrimonio = 0',{periodo_actual:actual,activo,pasivo,patrimonio:pat,diferencia:d},Math.abs(d)>1?'El balance no cierra matematicamente en el periodo actual.':'Activo, pasivo y patrimonio cierran matematicamente en el periodo actual.',Math.abs(d)>1?'La diferencia debe resolverse antes de utilizar el balance como base de conclusiones.':'El cierre matematico valida la aritmetica basica, pero no demuestra por si solo la razonabilidad economica de las cuentas.');
    }
    if(has(ac,anc,activo)){
      const d=activo-(ac+anc);
      if(Math.abs(d)>1)add(a,'inconsistencia','crit','Composicion del activo no concilia — '+actual,'Activo total = Activo corriente + Activo no corriente',{periodo_actual:actual,activo,activo_corriente:ac,activo_no_corriente:anc,diferencia:d},'Los subtotales del activo no reconstruyen el total informado.','Debe revisarse la totalizacion o la clasificacion de partidas.');
      else add(a,'conciliacion','info','Activo total conciliado — '+actual,'Activo corriente + Activo no corriente = Activo total',{periodo_actual:actual,activo_corriente:ac,activo_no_corriente:anc,activo_total:activo,diferencia:d},'La estructura del activo se puede reconstruir con los subtotales informados.','La estructura basica del activo es matematicamente consistente.');
    }
    if(has(pc,pnc,pasivo)){
      const d=pasivo-(pc+pnc);
      if(Math.abs(d)>1)add(a,'inconsistencia','crit','Composicion del pasivo no concilia — '+actual,'Pasivo total = Pasivo corriente + Pasivo no corriente',{periodo_actual:actual,pasivo_corriente:pc,pasivo_no_corriente:pnc,pasivo_total:pasivo,diferencia:d},'Los subtotales del pasivo no reconstruyen el total informado.','Debe identificarse la cuenta o reclasificacion que explica la diferencia.');
      else add(a,'conciliacion','info','Pasivo total conciliado — '+actual,'Pasivo corriente + Pasivo no corriente = Pasivo total',{periodo_actual:actual,pasivo_corriente:pc,pasivo_no_corriente:pnc,pasivo_total:pasivo,diferencia:d},'El pasivo total se reconstruye mediante sus componentes.','La estructura basica del pasivo es matematicamente consistente.');
    }
    const ventas=val(r,'ventas',actual),costo=val(r,'costo_ventas',actual),bruto=val(r,'resultado_bruto',actual);
    if(has(ventas,costo,bruto)){
      const esperado=ventas-costo,d=bruto-esperado;
      add(a,'inconsistencia',Math.abs(d)>1?'crit':'info','Resultado bruto '+(Math.abs(d)>1?'no ':'')+'conciliado — '+actual,'Resultado bruto = Ventas − Costo de ventas',{periodo_actual:actual,ventas,costo_ventas:costo,resultado_bruto:bruto,resultado_esperado:esperado,diferencia:d},Math.abs(d)>1?'El resultado bruto publicado no coincide con la relacion entre ventas y costo.':'El resultado bruto concilia con ventas y costo de ventas.',Math.abs(d)>1?'Puede existir una reclasificacion, componente adicional del costo o error de carga; debe verificarse antes de evaluar el margen.':'La aritmetica del margen bruto es consistente.');
    }
    const rn=val(r,'resultado_neto',actual),re=val(b,'resultado_ejercicio',actual);
    if(has(rn,re)){
      const d=rn-re;
      if(Math.abs(d)>1)add(a,'inconsistencia','crit','Resultado del ejercicio no coincide entre estados — '+actual,'Resultado neto = Resultado del ejercicio en patrimonio',{periodo_actual:actual,resultado_neto:rn,resultado_ejercicio:re,diferencia:d},'El resultado final no coincide entre Estado de Resultados y Balance.','Debe verificarse cierre, apropiacion del resultado o carga de periodos.');
      else add(a,'conciliacion','info','Resultado del ejercicio conciliado — '+actual,'Resultado neto = Resultado del ejercicio',{periodo_actual:actual,resultado_neto:rn,resultado_ejercicio:re,diferencia:d},'El resultado final coincide entre Estado de Resultados y patrimonio.','Existe consistencia entre ambos estados para este componente.');
    }
  }

  function resultados(data,a,actual,previous){
    const r=data.resultados;
    const v=val(r,'ventas',actual),br=val(r,'resultado_bruto',actual),g=val(r,'gastos_comerciales',actual),eb=val(r,'ebitda',actual),ebit=val(r,'ebit',actual),int=val(r,'intereses_gasto',actual),net=val(r,'resultado_neto',actual),pret=val(r,'resultado_antes_impuesto',actual),tax=val(r,'impuesto_renta',actual);
    if(has(v,br)&&v!==0){const m=br/v*100;if(m<0)add(a,'inconsistencia','crit','Margen bruto negativo — '+actual,'Resultado bruto / Ventas × 100',{periodo_actual:actual,ventas:v,resultado_bruto:br,margen_pct:m},'El costo de ventas supera las ventas del periodo actual.','Debe revisarse precio, costo de mercaderias, valorizacion de inventarios y composicion de ventas.');}
    if(has(v,eb)&&v!==0&&eb<0)add(a,'inconsistencia','crit','EBITDA negativo — '+actual,'EBITDA / Ventas × 100',{periodo_actual:actual,ventas:v,ebitda:eb,margen_ebitda_pct:eb/v*100},'La operacion actual no genera excedente antes de depreciaciones y amortizaciones.','Debe determinarse si el deterioro proviene del margen bruto, volumen, gastos operativos o una combinacion.');
    if(has(ebit,eb)&&eb<ebit)add(a,'inconsistencia','warn','Secuencia EBITDA / EBIT requiere revision — '+actual,'EBITDA ≥ EBIT',{periodo_actual:actual,ebitda:eb,ebit,diferencia:eb-ebit},'El EBITDA informado queda por debajo del EBIT, relacion que normalmente requiere una explicacion de la definicion utilizada.','Debe verificarse la composicion del EBITDA y el tratamiento de depreciaciones y amortizaciones.');
    if(has(eb,int)&&int>0){const c=eb/int;if(c<1)add(a,'inconsistencia','crit','Cobertura de intereses insuficiente — '+actual,'EBITDA / Intereses',{periodo_actual:actual,ebitda:eb,intereses:int,cobertura:c},'La generacion operativa no alcanza para cubrir los intereses financieros.','La capacidad actual de servicio financiero se encuentra bajo presion. Debe contrastarse con caja, deuda y refinanciacion.');else if(c<1.5)add(a,'hallazgo','warn','Cobertura de intereses ajustada — '+actual,'EBITDA / Intereses',{periodo_actual:actual,ebitda:eb,intereses:int,cobertura:c},'Los intereses estan cubiertos, pero con margen reducido.','Una disminucion moderada de la generacion operativa podria comprometer la cobertura.');}
    if(has(v,net)&&v!==0&&net<0)add(a,'hallazgo','imp','Resultado neto negativo — '+actual,'Resultado neto / Ventas × 100',{periodo_actual:actual,ventas:v,resultado_neto:net,margen_neto_pct:net/v*100},'El periodo actual termina con perdida.','Debe identificarse cuanto de la perdida proviene de la operacion, del resultado financiero, diferencia de cambio u otros componentes.');
    if(has(br,g,ebit)&&Math.abs((br-g)-ebit)>1)add(a,'inconsistencia','warn','Resultado operativo requiere conciliacion — '+actual,'EBIT = Resultado bruto − Gastos operativos',{periodo_actual:actual,resultado_bruto:br,gastos_operativos:g,ebit:ebit,ebit_esperado:br-g,diferencia:ebit-(br-g)},'El EBIT informado no coincide con el resultado bruto menos los gastos operativos identificados.','Puede existir una partida operativa adicional o una definicion distinta de EBIT; debe abrirse la composicion.');
    if(has(pret,tax,net)&&Math.abs((pret-tax)-net)>1)add(a,'inconsistencia','warn','Resultado neto requiere conciliacion — '+actual,'Resultado neto = Resultado antes de impuesto − Impuesto',{periodo_actual:actual,resultado_antes_impuesto:pret,impuesto_renta:tax,resultado_neto:net,resultado_esperado:pret-tax,diferencia:net-(pret-tax)},'El resultado neto no se reconstruye con las partidas fiscales identificadas.','Debe verificarse otros resultados, impuestos diferidos o componentes no incluidos en la normalizacion.');
    if(previous){
      const vp=val(r,'ventas',previous),bp=val(r,'resultado_bruto',previous),ep=val(r,'ebitda',previous),np=val(r,'resultado_neto',previous);
      if(has(v,vp,br,bp)&&v!==0&&vp!==0){const ma=br/v*100,mp=bp/vp*100,d=ma-mp;if(Math.abs(d)>=5)add(a,'tendencia',d<0?'warn':'info','Margen bruto '+(d<0?'se deteriora':'mejora')+' en el periodo actual — '+actual,'Margen bruto actual vs. antecedente',{periodo_actual:actual,margen_actual_pct:ma,margen_anterior_pct:mp,cambio_puntos:d,ventas_actuales:v,ventas_anteriores:vp},d<0?'El periodo actual convierte una menor proporcion de ventas en resultado bruto.':'El periodo actual mejora la proporcion de ventas convertida en resultado bruto.',d<0?'La variacion requiere identificar si el origen esta en precios, costos o mezcla comercial.':'La mejora debe contrastarse con precios, costos y mezcla para determinar su sostenibilidad.');}
      if(has(eb,ep)&&ep!==0){const d=pct(eb,ep);if(d!==null&&Math.abs(d)>=20)add(a,'tendencia',d<0?'warn':'info','Generacion operativa '+(d<0?'se deteriora':'mejora')+' en el periodo actual — '+actual,'Variacion EBITDA actual vs. antecedente',{periodo_actual:actual,ebitda_actual:eb,ebitda_anterior:ep,variacion_pct:d},d<0?'La generacion operativa cae materialmente frente al antecedente.':'La generacion operativa mejora materialmente frente al antecedente.',d<0?'Debe determinarse si la causa esta en ventas, margen o gastos.':'Debe determinarse si la mejora proviene de actividad, margen o estructura de gastos.');}
      if(has(net,np)&&np!==0){const d=pct(net,np);if(d!==null&&(Math.abs(d)>=30||(np<0&&net>0)||(np>0&&net<0)))add(a,'tendencia',net<0?'warn':'info','Resultado neto '+(net<0?'se deteriora':'mejora')+' en el periodo actual — '+actual,'Variacion del resultado neto actual vs. antecedente',{periodo_actual:actual,resultado_actual:net,resultado_anterior:np,variacion_pct:d},net<0?'El resultado final se encuentra bajo presion en el periodo actual.':'El resultado final mejora en el periodo actual.',net<0?'Debe separarse el efecto operativo del financiero y de otros resultados.':'La mejora debe contrastarse con la generacion operativa para evaluar su calidad.');}
    }
  }

  function capitalTrabajo(data,a,actual,previous){
    if(!previous)return;
    const b=data.balance,r=data.resultados;
    const ventas=val(r,'ventas',actual),ventas0=val(r,'ventas',previous),inv=val(b,'inventarios',actual),inv0=val(b,'inventarios',previous),cli=val(b,'creditos_ventas',actual),cli0=val(b,'creditos_ventas',previous),prov=val(b,'proveedores',actual),prov0=val(b,'proveedores',previous);
    const dv=pct(ventas,ventas0),di=pct(inv,inv0),dc=pct(cli,cli0),dp=pct(prov,prov0);
    if(dv!==null&&di!==null){const gap=di-dv;if(gap>30)add(a,'correlacion','imp','Inventarios evolucionan por encima de las ventas — '+actual,'Variacion inventarios vs. variacion ventas',{periodo_actual:actual,ventas_actuales:ventas,inventarios_actuales:inv,variacion_ventas_pct:dv,variacion_inventarios_pct:di,brecha_puntos:gap},'El stock cambia a una velocidad materialmente superior a la actividad comercial.','Puede existir acumulacion, menor rotacion, compras anticipadas o sobrestock. Debe verificarse la realizacion y valorizacion de existencias.');else if(gap<-30)add(a,'correlacion','info','Inventarios evolucionan por debajo de las ventas — '+actual,'Variacion inventarios vs. variacion ventas',{periodo_actual:actual,ventas_actuales:ventas,inventarios_actuales:inv,variacion_ventas_pct:dv,variacion_inventarios_pct:di,brecha_puntos:gap},'Las ventas evolucionan por encima del stock.','La relacion puede ser favorable si no existe riesgo de quiebre de abastecimiento.');}
    if(dv!==null&&dc!==null){const gap=dc-dv;if(gap>20)add(a,'correlacion','imp','Cartera comercial crece mas rapido que las ventas — '+actual,'Variacion de creditos vs. variacion de ventas',{periodo_actual:actual,ventas_actuales:ventas,creditos_actuales:cli,variacion_ventas_pct:dv,variacion_creditos_pct:dc,brecha_puntos:gap},'Los creditos comerciales aumentan proporcionalmente mas que las ventas.','Puede indicar extension de plazos o menor velocidad de cobranza. Debe verificarse antiguedad y recuperabilidad de cartera.');}
    if(dv!==null&&dp!==null){const gap=dp-dv;if(Math.abs(gap)>=20)add(a,'correlacion',gap<0?'warn':'info','Proveedores evolucionan '+(gap<0?'por debajo':'por encima')+' de las ventas — '+actual,'Variacion de proveedores vs. variacion de ventas',{periodo_actual:actual,ventas_actuales:ventas,proveedores_actuales:prov,variacion_ventas_pct:dv,variacion_proveedores_pct:dp,brecha_puntos:gap},gap<0?'La deuda comercial cae o crece menos que la actividad.':'La deuda comercial acompana o supera la actividad comercial.',gap<0?'Debe verificarse si la reduccion proviene de pagos reales, revaluaciones, reclasificaciones o una combinacion.':'Debe contrastarse con compras, inventarios y pagos para determinar si representa financiamiento operativo.');}
    const fx=val(r,'diferencia_cambio',actual);
    if(has(prov,prov0,fx)){const reduccion=prov0-prov,absfx=Math.abs(fx),gap=Math.abs(reduccion-absfx);if(reduccion>0&&absfx>0&&gap<=Math.max(100000,absfx*0.02))add(a,'correlacion','crit','Reduccion de proveedores y diferencia de cambio presentan coincidencia material — '+actual,'Disminucion de proveedores vs. diferencia de cambio',{periodo_actual:actual,proveedores_anterior:prov0,proveedores_actuales:prov,reduccion_proveedores:reduccion,diferencia_cambio:fx,diferencia_absoluta:absfx,brecha:gap},'La disminucion de proveedores es practicamente equivalente al importe de la diferencia de cambio del periodo.','Esto constituye una señal fuerte de que parte de la reduccion del pasivo podria ser una reexpresion contable y no una salida de efectivo. Debe verificarse en el mayor y auxiliares.');}
  }

  function flujo(data,a,actual,previous){
    const b=data.balance,r=data.resultados,f=data.flujo;if(!f)return;
    const caja=val(b,'caja_bancos',actual),caja0=previous?val(b,'caja_bancos',previous):null,fin=val(f,'efectivo_final',actual),ini=val(f,'efectivo_inicial',actual),net=val(f,'flujo_neto',actual),fo=val(f,'flujo_operativo',actual),fi=val(f,'flujo_inversion',actual),ff=val(f,'flujo_financiamiento',actual);
    if(has(ini,net,fin)){const d=fin-(ini+net);add(a,'conciliacion',Math.abs(d)>1?'crit':'info','Flujo de efectivo '+(Math.abs(d)>1?'no ':'')+'reconcilia caja final — '+actual,'Efectivo inicial + Flujo neto = Efectivo final',{periodo_actual:actual,efectivo_inicial:ini,flujo_neto:net,efectivo_final:fin,diferencia:d},Math.abs(d)>1?'El flujo no reconstruye matematicamente su efectivo final.':'El flujo reconstruye matematicamente su efectivo final.',Math.abs(d)>1?'Debe revisarse la suma de actividades o movimientos no incluidos.':'La aritmetica interna del flujo es consistente.');}
    if(has(caja,fin)){const d=caja-fin;if(Math.abs(d)>1)add(a,'inconsistencia','crit','Caja del Balance no coincide con efectivo final del Flujo — '+actual,'Caja Balance = Efectivo final Flujo',{periodo_actual:actual,caja_balance:caja,efectivo_final:fin,diferencia:d},'El saldo final de efectivo difiere entre Balance y Flujo.','Debe identificarse la cuenta de efectivo utilizada y cualquier reclasificacion bancaria.');else add(a,'conciliacion','info','Caja Balance y Flujo conciliados — '+actual,'Caja Balance = Efectivo final Flujo',{periodo_actual:actual,caja_balance:caja,efectivo_final:fin,diferencia:d},'El saldo final de efectivo coincide entre estados.','La conciliacion de caja es consistente.');}
    if(previous&&has(caja,caja0)&&has(fo,fi,ff)){const dc=caja-caja0,dflow=fo+fi+ff;if(Math.abs(dc-dflow)>1)add(a,'inconsistencia','warn','Variacion de caja no concilia con actividades del Flujo — '+actual,'Δ Caja = Flujo operativo + inversion + financiamiento',{periodo_actual:actual,caja_anterior:caja0,caja_actual:caja,variacion_caja:dc,flujo_operativo:fo,flujo_inversion:fi,flujo_financiamiento:ff,flujo_actividades:dflow,diferencia:dc-dflow},'La variacion de caja del Balance no coincide con la suma de las actividades del Flujo.','Debe revisarse diferencia de cambio, reclasificaciones o movimientos no presentados.');}
    const capex=val(f,'capex',actual),ppe=val(b,'ppe',actual),ppe0=previous?val(b,'ppe',previous):null;
    if(has(capex,ppe,ppe0)){const delta=ppe-ppe0,gross=Math.abs(capex);if(Math.abs(delta-gross)>Math.max(1,gross*0.15))add(a,'correlacion','warn','CAPEX y movimiento de activo fijo requieren conciliacion — '+actual,'Variacion PPE vs. CAPEX',{periodo_actual:actual,ppe_anterior:ppe0,ppe_actual:ppe,variacion_ppe:delta,capex_informado:capex,diferencia:delta-gross},'La inversion informada no se explica directamente por el movimiento del activo fijo.','Debe verificarse depreciacion, bajas, revaluaciones, diferencias de cambio y compras no monetarias.');else add(a,'correlacion','info','CAPEX y movimiento de activo fijo presentan correlacion — '+actual,'Variacion PPE vs. CAPEX',{periodo_actual:actual,ppe_anterior:ppe0,ppe_actual:ppe,variacion_ppe:delta,capex_informado:capex},'El importe de inversion es compatible con el incremento del activo fijo.','La inversion presenta respaldo contable; resta verificar la fuente monetaria que la financio.');}
    if(has(capex,fo)&&capex<0&&fo<Math.abs(capex)){const financ=ff??0,gap=Math.abs(capex)-Math.max(0,fo)-Math.max(0,financ);if(gap>1)add(a,'flujo','crit','Fuente de fondos para CAPEX no identificada completamente — '+actual,'CAPEX − Flujo operativo − Financiamiento',{periodo_actual:actual,capex,flujo_operativo:fo,flujo_financiamiento:financ,brecha_financiacion:gap},'La inversion supera la capacidad de financiamiento monetario identificable en el periodo.','Debe identificarse deuda nueva, aportes, venta de activos u otra fuente. Una variacion contable del pasivo no debe considerarse efectivo sin evidencia.');}
    const ventas=val(r,'ventas',actual),cli=val(b,'creditos_ventas',actual),cli0=previous?val(b,'creditos_ventas',previous):null,cobros=val(f,'cobros_clientes',actual);
    if(has(ventas,cli,cli0,cobros)){const est=ventas+cli0-cli,d=cobros-est;if(Math.abs(d)>Math.max(100000,Math.abs(est)*0.05))add(a,'flujo','warn','Cobros de clientes requieren conciliacion — '+actual,'Cobros estimados = Ventas + Clientes iniciales − Clientes finales',{periodo_actual:actual,ventas,creditos_anterior:cli0,creditos_actuales:cli,cobranza_reconstruida:est,cobros_informados:cobros,diferencia:d},'El cobro informado difiere materialmente de la cobranza reconstruida a partir de ventas y cartera.','La diferencia puede contener IVA, notas de credito, otros movimientos o reclasificaciones; requiere conciliacion auxiliar.');}
    const cogs=val(r,'costo_ventas',actual),inv=val(b,'inventarios',actual),inv0=previous?val(b,'inventarios',previous):null,prov=val(b,'proveedores',actual),prov0=previous?val(b,'proveedores',previous):null,pay=val(f,'pagos_proveedores',actual);
    if(has(cogs,inv,inv0,prov,prov0,pay)){const compras=cogs+inv-inv0,pagEst=compras+prov0-prov,d=pay-pagEst;if(Math.abs(d)>Math.max(100000,Math.abs(pagEst)*0.05))add(a,'flujo','warn','Pagos a proveedores requieren conciliacion — '+actual,'Compras = Costo de ventas + Δ Inventarios; Pagos = Compras + Proveedores iniciales − finales',{periodo_actual:actual,costo_ventas:cogs,inventario_anterior:inv0,inventario_actual:inv,compras_estimadas:compras,proveedores_anterior:prov0,proveedores_actuales:prov,pagos_estimados:pagEst,pagos_proveedores_informados:pay,diferencia:d},'El pago informado no coincide con el pago reconstruido desde compras e impacto de proveedores.','Debe verificarse diferencia de cambio, impuestos, anticipos, compras no monetarias y reclasificaciones.');else add(a,'conciliacion','info','Pagos a proveedores conciliados — '+actual,'Compras y variacion de proveedores',{periodo_actual:actual,compras_estimadas:compras,pagos_estimados:pagEst,pagos_proveedores_informados:pay,diferencia:d},'El pago informado es compatible con la reconstruccion contable.','La relacion entre compras, inventarios, proveedores y pagos resulta consistente.');}
    const int=val(r,'intereses_gasto',actual),ip=val(b,'intereses_a_pagar',actual),ip0=previous?val(b,'intereses_a_pagar',previous):null,ipaid=val(f,'intereses_pagados',actual);
    if(has(int,ip,ip0,ipaid)){const esperado=ipaid+(ip-ip0),d=int-esperado;if(Math.abs(d)>Math.max(100000,Math.abs(int)*0.05))add(a,'inconsistencia','warn','Intereses devengados y pagados requieren conciliacion — '+actual,'Intereses devengados = Intereses pagados + Δ Intereses a pagar',{periodo_actual:actual,intereses_gasto:int,intereses_pagados:ipaid,intereses_pagar_anterior:ip0,intereses_pagar_actual:ip,intereses_reconstruidos:esperado,diferencia:d},'El gasto financiero no se explica por pagos mas variacion de intereses pendientes.','Debe revisarse devengamiento, capitalizacion o clasificacion de intereses.');}
  }

  function patrimonio(data,a,actual,previous){
    if(!previous)return;
    const b=data.balance,r=data.resultados,p=val(b,'total_patrimonio',actual),p0=val(b,'total_patrimonio',previous),net=val(r,'resultado_neto',actual),cap=val(b,'capital',actual),cap0=val(b,'capital',previous),res=val(b,'resultados_acumulados',actual),res0=val(b,'resultados_acumulados',previous);
    if(has(p,p0,net)){const delta=p-p0,dc=has(cap,cap0)?cap-cap0:0,dr=has(res,res0)?res-res0:0,unexplained=delta-net-dc-dr;if(Math.abs(unexplained)>Math.max(100000,Math.abs(delta)*0.1))add(a,'correlacion','warn','Evolucion patrimonial requiere explicar movimientos no identificados — '+actual,'Δ Patrimonio = Resultado + Δ Capital + Δ Resultados acumulados + otros',{periodo_actual:actual,patrimonio_anterior:p0,patrimonio_actual:p,resultado_neto:net,cambio_capital:dc,cambio_resultados_acumulados:dr,movimiento_no_explicado:unexplained},'El cambio patrimonial no queda explicado por el resultado y los movimientos patrimoniales identificados.','Debe verificarse aportes, retiros, dividendos, ajustes de ejercicios anteriores, revaluaciones u otros movimientos de patrimonio.');}
  }

  function ejecutar(data){
    const years=yearsOf(data),actual=years.at(-1)||null,previous=actual?previousOf(data,actual):null,h=[];
    if(!actual)return{hallazgos:[],years,actual:null,previous:null};
    integridad(data,h,actual);resultados(data,h,actual,previous);capitalTrabajo(data,h,actual,previous);flujo(data,h,actual,previous);patrimonio(data,h,actual,previous);
    const rank={crit:0,imp:1,warn:2,info:3};h.sort((x,y)=>(rank[x.nivel]??9)-(rank[y.nivel]??9));
    return{hallazgos:h,years,actual,previous};
  }
  return{ejecutar,yearsOf};
})();
