/* DIAGNÓSTICO CREDITICIO FINAL — SOLO PERÍODO ACTUAL */
(function(){
 const $=id=>document.getElementById(id),norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const N=v=>{if(v==null||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');let x=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(x)?x:null};
 const money=x=>x==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(x),pct=x=>(x*100).toFixed(1)+'%';const cols=[2,5,8];
 const A={activo:['total activo','activo total'],pasivo:['total pasivo','pasivo total'],patrimonio:['patrimonio neto','total patrimonio neto','patrimonio'],caja:['disponible (caja y bancos)','disponible caja y bancos','caja y bancos','disponible','caja'],clientes:['creditos comerciales - cp (clientes)','creditos comerciales cp (clientes)','creditos comerciales - cp','creditos comerciales cp','clientes'],inventario:['inventario','inventarios'],proveedores:['deudas comerciales - cp (proveedores)','deudas comerciales cp (proveedores)','deudas comerciales - cp','deudas comerciales cp','proveedores'],acreedores:['acreedores varios','otras cuentas por pagar','otros acreedores'],impuestos:['impuestos por pagar','tributos por pagar','impuestos y tasas por pagar'],deuda:['deudas financieras - cp','deudas financieras cp','deuda financiera - cp','deuda financiera cp','deudas financieras - lp','deudas financieras lp','deuda financiera - lp','deuda financiera lp'],ventas:['ventas netas','ventas'],costo:['costo de ventas','costos de ventas'],intereses:['intereses financieros pagados','intereses financieros','intereses pagados'],resultado:['resultado neto','resultado del ejercicio','ganancia del ejercicio','perdida del ejercicio'],flowClientes:['variacion cuentas a cobrar comerciales cp','variacion cuentas a cobrar comerciales'],flowNet:['variacion neta de caja']};
 function read(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return Promise.resolve(null);return f.arrayBuffer().then(b=>{const wb=XLSX.read(b,{type:'array',raw:true,blankrows:true});const name=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0];return XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:true})})}
 function find(r,ls){const w=ls.map(norm);for(let i=0;i<r.length;i++){const c=[0,1,2,3].map(j=>norm(r[i]?.[j]));if(w.some(x=>c.includes(x)))return i}for(let i=0;i<r.length;i++){const c=[0,1,2,3].map(j=>norm(r[i]?.[j]));if(w.some(x=>c.some(z=>z===x||z.startsWith(x+' ')||z.endsWith(' '+x))))return i}return -1}
 function get(r,map){const d={};for(const[k,ls]of Object.entries(map)){const i=find(r,ls);d[k]=i<0?null:cols.map(c=>N(r[i]?.[c]))}return d}const v=(d,k,i)=>d[k]?.[i],has=x=>x!=null&&Number.isFinite(x);
 function analyze(d){const i=2,p=1,a=[];const act=v(d,'activo',i),pas=v(d,'pasivo',i),pat=v(d,'patrimonio',i);if(has(act)&&has(pas)&&has(pat)){const dif=act-pas-pat;if(Math.abs(dif)>Math.max(Math.abs(act)*.005,1))a.push(['ALTA','Balance no cierra','Activo difiere de Pasivo + Patrimonio por G. '+money(dif),'La ecuación patrimonial no cierra. Antes de evaluar solvencia hay que aclarar la diferencia.','Activo; Pasivo; Patrimonio.','No aumentar la línea hasta aclararlo.'])}
 const sales=v(d,'ventas',i),sales0=v(d,'ventas',p),cost=v(d,'costo',i),cost0=v(d,'costo',p),cli=v(d,'clientes',i),cli0=v(d,'clientes',p),inv=v(d,'inventario',i),inv0=v(d,'inventario',p),prov=v(d,'proveedores',i),prov0=v(d,'proveedores',p),pas0=v(d,'pasivo',p),debt=v(d,'deuda',i),inter=v(d,'intereses',i),res=v(d,'resultado',i),cash=v(d,'caja',i),cash0=v(d,'caja',p),flowCli=v(d,'flowClientes',i);
 if(has(sales)&&has(sales0)&&sales0!==0){const g=(sales-sales0)/Math.abs(sales0);if(g<-.15)a.push(['MEDIA','Ventas caen significativamente','Ventas 2025 G. '+money(sales)+' frente a G. '+money(sales0)+' en 2024: variación '+pct(g)+'.','La actividad comercial cayó y puede reducir la generación de fondos disponible para pagar deuda.','Ventas; Resultado; Flujo.','No aumentar la línea sin considerar el deterioro.'])}
 if(has(cli)&&has(sales)&&sales>0){
   const days=cli/sales*365,days0=has(cli0)&&has(sales0)&&sales0>0?cli0/sales0*365:null;
   const clientGrowth=has(cli0)&&cli0!==0?(cli-cli0)/Math.abs(cli0):null;
   const salesGrowth=has(sales0)&&sales0!==0?(sales-sales0)/Math.abs(sales0):null;
   const clientVariation=has(cli0)?cli-cli0:null;
   const flowOK=has(flowCli)&&has(clientVariation)&&Math.abs(flowCli-clientVariation)<=1;
   if(days>90||(days0!=null&&days>days0*1.5&&days>45)){
     let calc='Clientes 2025 G. '+money(cli)+' ÷ Ventas 2025 G. '+money(sales)+' × 365 = '+days.toFixed(1)+' días';
     if(days0!=null)calc+='; en 2024: G. '+money(cli0)+' ÷ G. '+money(sales0)+' × 365 = '+days0.toFixed(1)+' días';
     let relation='El saldo de clientes creció '+(clientGrowth==null?'—':pct(clientGrowth))+' mientras las ventas '+(salesGrowth==null?'—':(salesGrowth>=0?'crecieron ':'cayeron ')+pct(Math.abs(salesGrowth)))+'.';
     if(clientVariation!=null)relation+=' El aumento de clientes fue G. '+money(clientVariation)+', que representa '+pct(clientVariation/Math.max(Math.abs(sales),1))+' de las ventas 2025.';
     if(flowOK)relation+=' El Flujo confirma el mismo movimiento: G. '+money(flowCli)+'/'+money(clientVariation)+', por lo que el aumento de créditos absorbió ese efectivo.';
     else if(has(flowCli))relation+=' El Flujo muestra G. '+money(flowCli)+' y el Balance G. '+money(clientVariation)+': existe una diferencia que también debe explicarse.';
     const why=(salesGrowth!=null&&clientGrowth!=null&&clientGrowth>salesGrowth*3)?'Los créditos a clientes crecieron mucho más rápido que las ventas. Esto significa que una parte creciente de las ventas quedó pendiente de cobro y redujo la conversión de ventas en efectivo.':'El plazo implícito aumentó y debe determinarse si responde a condiciones comerciales normales o a acumulación de saldos.';
     a.push(['MEDIA','Clientes: aumento de plazo',calc,relation+' '+why,'Relación automática: Clientes ↔ Ventas ↔ Flujo. IVA solo se incorpora cuando existe una base IVA identificable en el archivo.','Si el aumento no se explica por la evolución comercial, pedir detalle de deuda de clientes.']);
   }
 }
 if(has(inv)&&has(cost)&&cost>0){const rot=cost/inv,rot0=has(inv0)&&has(cost0)&&cost0>0?cost0/inv0:null;if(rot<1.5||(rot0!=null&&rot<rot0*.6))a.push(['MEDIA','Inventario: rotación deteriorada','Inventario 2025 G. '+money(inv)+' ÷ Costo de ventas G. '+money(cost)+' = '+rot.toFixed(2)+' veces'+(rot0!=null?' frente a '+rot0.toFixed(2)+' veces en 2024':'')+'.','El inventario está consumiendo más capital en relación con el costo vendido.','Inventario ↔ Costo de ventas ↔ Caja.','Revisar antes de aumentar exposición; pedir detalle solo si el comportamiento no se explica.'])}
 if(has(prov)&&has(prov0)&&has(cost)&&has(inv)&&has(inv0)){const compras=cost+inv-inv0,dp=prov-prov0;if(compras>0&&dp<0&&Math.abs(dp)>compras*.25)a.push(['MEDIA','Proveedores disminuyen pese a compras relevantes','Compras reconstruidas = Costo de ventas G. '+money(cost)+' + (Inventario final G. '+money(inv)+' − inicial G. '+money(inv0)+') = G. '+money(compras)+'. Proveedores disminuyeron G. '+money(Math.abs(dp))+'.','Se compró un volumen importante pero el saldo con proveedores cayó. Puede ser pago al contado, cancelación o traslado de obligaciones a otras cuentas.','Costo de ventas ↔ Inventario ↔ Proveedores ↔ Caja/Deuda.','Si el Flujo no explica los pagos, pedir detalle de deuda con proveedores.'])}
 if(has(pas)&&has(pas0)&&has(sales)&&has(sales0)&&sales0!==0&&pas0!==0){const gs=(sales-sales0)/Math.abs(sales0),gp=(pas-pas0)/Math.abs(pas0),r=pas/sales,r0=pas0/sales0;if(gs>.15&&gp<-.15&&r<r0*.7)a.push(['ALTA','Posible omisión o subregistro de pasivos','Ventas aumentaron '+pct(gs)+' pero el Pasivo disminuyó '+pct(Math.abs(gp))+'. Pasivo/Ventas pasó de '+pct(r0)+' a '+pct(r)+'.','El negocio crece mientras las obligaciones registradas disminuyen. No prueba un pasivo omitido, pero la relación es suficientemente anormal para comprobar si existen obligaciones en proveedores, acreedores, impuestos o bancos que no estén reflejadas.','Ventas ↔ Pasivo ↔ Proveedores ↔ Acreedores ↔ Impuestos ↔ Deuda financiera ↔ Flujo.','Si no existe una explicación en los estados, pedir detalle de deuda con proveedores y referencias bancarias.'])}
 if(has(inter)&&has(debt)&&debt===0&&inter!==0)a.push(['ALTA','Intereses sin deuda financiera al cierre','Intereses registrados G. '+money(inter) +' y deuda financiera al cierre G. 0.','Puede existir deuda cancelada durante el año o una obligación financiera no visible al cierre.','Intereses ↔ Deuda financiera ↔ Flujo de deuda.','Aclarar el origen mediante los movimientos del año.'])
 if(has(res)&&has(cash)&&has(cash0)&&res>0&&cash<cash0){const ca=(cash0-cash)/Math.max(res,1);if(ca>.5)a.push(['MEDIA','Resultado positivo pero Caja disminuye','Resultado positivo G. '+money(res)+' mientras Caja/Bancos disminuye G. '+money(cash0-cash)+'.','La utilidad no se convirtió íntegramente en efectivo. El sistema debe comprobar si la causa está en clientes, inventario, inversiones o pagos de deuda.','Resultado ↔ Clientes ↔ Inventario ↔ Deuda ↔ Flujo.','Revisar el puente de efectivo antes de decidir.'])}
 return a}
 function render(r){const d=get(r,A),a=analyze(d),high=a.filter(x=>x[0]==='ALTA').length;const grade=high>=2?'MALO':high===1?'REGULAR':a.length>=2?'REGULAR':a.length===1?'BIEN':'EXCELENTE';const text=grade==='MALO'?'Existen varias señales relevantes. No conviene aumentar la exposición hasta aclararlas.':grade==='REGULAR'?'Existen señales que pueden afectar el riesgo y deben revisarse antes de decidir.':grade==='BIEN'?'Hay una señal puntual, sin una inconsistencia principal.':'No se detectan anomalías relevantes con la información disponible.';const s=document.createElement('section');s.className='card';s.id='diagnosticoFinal';s.innerHTML='<h2>4. CONCLUSIÓN CREDITICIA — 2025</h2><div class="body"><div class="final-grade '+(grade==='MALO'?'g-bad':grade==='REGULAR'?'g-warn':grade==='BIEN'?'g-good':'g-excellent')+'"><small>RESULTADO DEL PERÍODO ACTUAL</small><strong>'+grade+'</strong><span>'+text+'</span></div>'+(a.length?'<h3>ALERTAS QUE REALMENTE IMPORTAN</h3><div class="final-alerts">'+a.slice(0,5).map((x,j)=>'<article class="final-alert"><div><b>'+(j+1)+'. '+esc(x[1])+'</b><em>'+x[0]+'</em></div><p><b>Qué calculó el sistema:</b> '+esc(x[2])+'</p><p><b>Qué encontró al relacionar las cuentas:</b> '+esc(x[3])+'</p><p><b>Relación utilizada:</b> '+esc(x[4])+'</p><p><b>Qué hacer:</b> '+esc(x[5])+'</p></article>').join('')+'</div>':'<div class="final-ok"><b>Sin alertas relevantes.</b><br>Los controles principales no muestran una señal que justifique profundizar.</div>')+'<div class="final-decision"><b>CRITERIO:</b> 2025 determina la conclusión. 2023 y 2024 se utilizan solamente para tendencia y deterioro.</div></div>';const aud=$('auditoria');if(aud){const old=$('diagnosticoFinal');if(old)old.remove();aud.appendChild(s)}else document.body.appendChild(s)}
 function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>read().then(r=>{if(r)render(r)}),650))}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
