/* V3 — capa de explicación documental.
   No pide documentos si Balance + Flujo ya explican la alerta.
*/
(function(){
 const $=id=>document.getElementById(id), norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
 const money=n=>n==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(n);
 const num=v=>{if(v==null||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');let n=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(n)?n:null};
 const aliases={deuda:['deudas financieras - cp','deudas financieras cp'],deudaLP:['deudas financieras - lp','deudas financieras lp'],intereses:['intereses financieros pagados'],cash:['disponible (caja y bancos)','disponible caja y bancos','caja y bancos','disponible'],cashFlow:['variacion neta de caja'],flowOp:['generacion (aplicacion) neta operativa'],flowClientes:['variacion cuentas a cobrar comerciales cp','variacion cuentas a cobrar comerciales'],flowDebtPay:['pago deudas financieras cp'],flowDebtNew:['nuevas deudas financieras cp'],resultado:['resultado neto total del ejercicio','resultado neto','resultado del ejercicio']};
 function find(rows,a){a=a.map(norm);for(let i=0;i<rows.length;i++){let s=norm(rows[i]?.[1]??rows[i]?.[0]);if(a.includes(s)||a.some(x=>s===x||s.startsWith(x+' ')))return i}return -1}
 function load(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return Promise.resolve(null);return f.arrayBuffer().then(b=>{const wb=XLSX.read(b,{type:'array',raw:true}),name=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0],rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null,raw:true,blankrows:true}),cols=[2,5,8],d={};for(const[k,a]of Object.entries(aliases)){const r=find(rows,a);d[k]=r<0?null:cols.map(c=>num(rows[r]?.[c]))}return d})}
 const v=(d,k,i)=>d[k]?.[i]??null;
 function explain(d){const i=2,p=1,totalDebt=(v(d,'deuda',i)||0)+(v(d,'deudaLP',i)||0),newDebt=v(d,'flowDebtNew',i)||0,payDebt=v(d,'flowDebtPay',i)||0,inter=v(d,'intereses',i),cash=v(d,'cash',i),cashP=v(d,'cash',p),flowOp=v(d,'flowOp',i),flowCash=v(d,'cashFlow',i),flowCli=v(d,'flowClientes',i),res=v(d,'resultado',i);
  return {interest:inter!=null&&inter!==0&&totalDebt===0&&newDebt-payDebt<0, cash:(res!=null&&res>0&&cash!=null&&cashP!=null&&cash<cashP&&(flowOp<0||flowCash!=null)), flowCli:flowCli!=null};
 }
 function apply(x){const sec=$('diagnosticoV2');if(!sec)return;sec.querySelectorAll('.v2-alert').forEach(card=>{const title=norm(card.querySelector('.v2-head b')?.textContent),action=card.querySelector('.v2-row.action span'),rows=[...card.querySelectorAll('.v2-row')];if(!action)return;let status='',text='';if(title.includes('intereses sin deuda')){status=x.interest?'EXPLICADA POR EL FLUJO':'NO EXPLICADA';text=x.interest?'El Flujo muestra cancelación neta de deuda durante el ejercicio. Por eso es coherente que existan intereses aunque la deuda final sea cero. No solicitar documentación adicional.':'El sistema no encuentra en la información presentada el movimiento que explique los intereses con deuda final cero. Revisar primero el Flujo; si continúa sin explicación, solicitar únicamente detalle de deuda y referencia bancaria.'}else if(title.includes('resultado positivo pero caja')){status=x.cash?'EXPLICADA POR EL FLUJO':'REQUIERE CONCILIACIÓN';text=x.cash?'El propio Flujo permite explicar la disminución de Caja/Bancos. No solicitar documentación adicional por esta alerta.':'La documentación presentada no permite explicar completamente la disminución de Caja/Bancos. Conciliar primero las variaciones del Balance y el Flujo; solo si queda una diferencia material, solicitar información específica.'}else if(title.includes('clientes')){status=x.flowCli?'EXPLICADA POR BALANCE + FLUJO':'PARCIALMENTE EXPLICADA';text=x.flowCli?'El aumento de Clientes está reflejado en el Flujo. La alerta ya está explicada como una aplicación de efectivo; no solicitar documentación adicional por el solo aumento del saldo.':'El Balance muestra el aumento, pero no existe confirmación suficiente en el Flujo. Comprobar IVA y flujo antes de solicitar detalle de clientes.'}else return;let old=card.querySelector('.v2-row.status');if(!old){old=document.createElement('div');old.className='v2-row status';card.insertBefore(old,action.parentElement)}old.innerHTML='<b>ESTADO DEL ANÁLISIS</b><span>'+status+'</span>';action.textContent=text;});}
 function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>load().then(d=>{if(d)apply(explain(d))}),900))}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
