/* MOTOR CREDITICIO V3 — conclusión del período actual.
   Los años anteriores sirven solo para tendencia. La acción documental se decide con los estados y el flujo cargados.
*/
(function(){
  const $=id=>document.getElementById(id);
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const num=v=>{if(v==null||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\s/g,'').replace(/[()]/g,'-');if(/^-?\d{1,3}(\.\d{3})+(,\d+)?$/.test(s))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'.');const n=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(n)?n:null};
  const money=n=>n==null?'—':new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(n);
  const pct=n=>n==null||!Number.isFinite(n)?'—':(n*100).toFixed(1)+'%';
  const spct=n=>n==null||!Number.isFinite(n)?'—':(n>=0?'+':'')+(n*100).toFixed(1)+'%';
  const days=n=>n==null||!Number.isFinite(n)?'—':n.toFixed(1)+' días';
  const growth=(a,b)=>a==null||b==null||b===0?null:(a-b)/Math.abs(b);
  const aliases={
    caja:['disponible (caja y bancos)','disponible caja y bancos','caja y bancos','disponible'],
    clientes:['creditos comerciales - cp (clientes)','creditos comerciales cp (clientes)'],
    inventario:['inventario'],
    proveedores:['deudas comerciales - cp (proveedores)','deudas comerciales cp (proveedores)'],
    acreedores:['acreedores varios'], impuestos:['impuestos por pagar','tributos por pagar','impuestos y tasas por pagar'],
    deuda:['deudas financieras - cp','deudas financieras cp'], deudaLP:['deudas financieras - lp','deudas financieras lp'],
    pasivo:['total pasivo'], ventas:['ventas netas'], costo:['costo de ventas'],
    resultado:['resultado neto total del ejercicio','resultado neto','resultado del ejercicio'], intereses:['intereses financieros pagados'],
    flowCaja:['variacion neta de caja'], flowClientes:['variacion cuentas a cobrar comerciales cp','variacion cuentas a cobrar comerciales'],
    flowProveedores:['variacion cuentas a pagar comerciales cp'], flowOp:['generacion (aplicacion) neta operativa'],
    flowDebtPay:['pago deudas financieras cp'], flowDebtNew:['nuevas deudas financieras cp']
  };
  function findRow(rows,a){const aa=a.map(norm);for(let r=0;r<rows.length;r++){const s=norm(rows[r]?.[1]??rows[r]?.[0]);if(aa.includes(s))return r}for(let r=0;r<rows.length;r++){const s=norm(rows[r]?.[1]??rows[r]?.[0]);if(aa.some(x=>s===x||s.startsWith(x+' ')||s.includes(x)))return r}return -1}
  function read(){const f=$('archivoUnico')?.files?.[0];if(!f||!window.XLSX)return Promise.resolve(null);return f.arrayBuffer().then(b=>{const wb=XLSX.read(b,{type:'array',raw:true,blankrows:true});const sh=wb.SheetNames.find(x=>norm(x)==='ee ff y eerr')||wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json(wb.Sheets[sh],{header:1,defval:null,raw:true,blankrows:true});const cols=[2,5,8];const year=v=>{const m=String(v??'').match(/(?:19|20)\d{2}/);return m?m[0]:null};let years=cols.map(c=>year(rows[4]?.[c]));if(years.some(x=>!x)){for(let r=0;r<12;r++){const y=cols.map(c=>year(rows[r]?.[c]));if(y.every(Boolean)){years=y;break}}}const d={years};for(const[k,a]of Object.entries(aliases)){const r=findRow(rows,a);d[k]=r<0?null:cols.map(c=>num(rows[r]?.[c]))}return d})}
  const v=(d,k,i)=>d[k]?.[i]??null;
  function analyze(d){
    const n=d.years?.length||3,i=n-1,p=n-2,cur=d.years?.[i]||$('ejercicio')?.value||'período actual',prev=d.years?.[p]||'período anterior',f=[];
    const add=(level,title,detected,meaning,accounts,action)=>f.push({level,title,detected,meaning,accounts,action});
    const sales=v(d,'ventas',i),salesP=v(d,'ventas',p),cost=v(d,'costo',i),costP=v(d,'costo',p),clients=v(d,'clientes',i),clientsP=v(d,'clientes',p),inv=v(d,'inventario',i),invP=v(d,'inventario',p),prov=v(d,'proveedores',i),provP=v(d,'proveedores',p),pass=v(d,'pasivo',i),passP=v(d,'pasivo',p),cash=v(d,'caja',i),cashP=v(d,'caja',p),res=v(d,'resultado',i),resP=v(d,'resultado',p),op=v(d,'flowOp',i),flowCli=v(d,'flowClientes',i),flowCash=v(d,'flowCaja',i),debt=(v(d,'deuda',i)||0)+(v(d,'deudaLP',i)||0),debtP=(v(d,'deuda',p)||0)+(v(d,'deudaLP',p)||0),newDebt=v(d,'flowDebtNew',i),payDebt=v(d,'flowDebtPay',i),inter=v(d,'intereses',i);
    const sg=growth(sales,salesP),cg=growth(clients,clientsP),ig=growth(inv,invP),pg=growth(prov,provP),passg=growth(pass,passP),clientDelta=clients!=null&&clientsP!=null?clients-clientsP:null,invDelta=inv!=null&&invP!=null?inv-invP:null,provDelta=prov!=null&&provP!=null?prov-provP:null;
    if(sg!=null&&sg<=-.15){
      const rg=growth(res,resP);add(sg<=-.30?'ALTA':'MEDIA','Ventas: deterioro de actividad',`Ventas: G. ${money(salesP)} → G. ${money(sales)} (${spct(sg)}). ${rg!=null?'Resultado neto: '+spct(rg)+'.':''} ${op!=null?'Generación operativa: G. '+money(op)+'.':''}`,`La caída comercial es más preocupante cuando también reduce resultado o generación operativa. El sistema cruza las tres cosas para saber si el deterioro llega a la capacidad de pago.`,`Ventas ↔ Resultado neto ↔ Flujo operativo ↔ Caja ↔ Clientes`,`Si ventas, resultado y flujo confirman deterioro, considerar reducción de exposición. Los 12 IVA se usan como confirmación de tendencia; no se piden documentos adicionales por esta alerta si los estados ya explican la caída.`)
    }
    if(clients!=null&&sales>0){
      const d0=clients/sales*365,dP=clientsP!=null&&salesP>0?clientsP/salesP*365:null,match=flowCli!=null&&clientDelta!=null&&Math.abs(flowCli-clientDelta)<=1,disproportion=cg!=null&&sg!=null&&cg>0&&cg>sg+0.20;
      if(d0>60||(dP!=null&&d0>dP+30)||disproportion){
        let det=`Clientes: G. ${money(clients)}; ventas: G. ${money(sales)}; saldo equivale a ${days(d0)} de ventas.`;if(dP!=null)det+=` En ${prev}: ${days(dP)}.`;if(cg!=null&&sg!=null)det+=` Clientes ${spct(cg)} vs ventas ${spct(sg)}.`;if(clientDelta!=null)det+=` Aumento de saldo: G. ${money(clientDelta)}.`;
        const meaning=match?`El aumento está explicado por el propio Flujo: G. ${money(flowCli)} pasó a cuentas a cobrar. Eso significa que la venta quedó registrada, pero ese importe todavía no se convirtió en efectivo. No es pérdida de dinero ni prueba de incobrabilidad.`:`El saldo aumentó y el sistema no encuentra en el Flujo una variación equivalente. Por eso todavía no puede determinar si se trata de ventas a plazo normales, cobros pendientes, reclasificaciones o un saldo que requiere explicación.`;
        const action=match?`NO PEDIR DOCUMENTACIÓN POR AHORA. El Balance + Ventas + Flujo ya explican el movimiento. La alerta queda como señal de mayor plazo, no como inconsistencia.`:`REVISAR INTERNAMENTE. Comparar Clientes, Ventas y Flujo del período. Solo si después de esa comprobación queda una diferencia material, pedir detalle de deuda de clientes.`;
        add('MEDIA','Clientes: aumento del plazo de cobro',det,meaning,`Clientes ↔ Ventas ↔ Flujo de cuentas a cobrar ↔ Caja`,action)
      }
    }
    if(inv!=null&&cost>0){const id=inv/cost*365,idP=invP!=null&&costP>0?invP/costP*365:null;if(id>180||(idP!=null&&id>idP+45)){const salesBad=sg!=null&&sg<0;add(salesBad?'ALTA':'MEDIA','Inventario: posible acumulación',`Inventario G. ${money(inv)}; costo G. ${money(cost)}; equivalente a ${days(id)}.`+(idP!=null?` Antes: ${days(idP)}.`:''),`El stock consume capital. Si además las ventas bajan, existe mayor riesgo de que parte del capital quede inmovilizado y no genere caja al ritmo esperado.`,`Inventario ↔ Costo de ventas ↔ Ventas ↔ Caja`,`Si ventas caen y el inventario no acompaña, considerar reducción de exposición. Pedir detalle de inventario solo si los estados e IVA no permiten explicar la situación.`)}}
    if(cost!=null&&inv!=null&&invP!=null&&prov!=null&&provP!=null){const purchases=cost+invDelta;if(purchases>0&&provDelta<0&&Math.abs(provDelta)>purchases*.20){const cashExplains=flowProveedores=>flowProveedores!=null&&Math.abs(flowProveedores+provDelta)<=1;add('MEDIA','Proveedores: compras y pagos a comprobar',`Compras reconstruidas: G. ${money(purchases)}; Proveedores: G. ${money(provP)} → G. ${money(prov)} (${spct(pg)}).`,`Las compras pueden haber sido pagadas durante el año o hechas al contado. La señal no prueba omisión; solo exige que el efectivo o el flujo expliquen cómo se financiaron esas compras.`,`Costo de ventas ↔ Inventario ↔ Proveedores ↔ Caja ↔ Flujo`,`Primero comprobar Caja/Flujo. Si el movimiento de efectivo explica los pagos, NO pedir documentación. Si no los explica y la diferencia es material, pedir únicamente detalle de deuda con proveedores.`)}}
    const otherNow=(v(d,'acreedores',i)||0)+(v(d,'impuestos',i)||0)+Math.max(prov||0,0)+debt,otherPrev=(v(d,'acreedores',p)||0)+(v(d,'impuestos',p)||0)+Math.max(provP||0,0)+debtP;
    if(passg!=null&&sg!=null&&passg<=-.20&&sg>=-.05&&otherPrev>0&&otherNow<otherPrev*.80)add('ALTA','Pasivos: posible omisión a comprobar',`Pasivo total: ${spct(passg)}; ventas: ${spct(sg)}. Proveedores + acreedores + impuestos + deuda también disminuyeron de forma importante.`,`No demuestra un pasivo omitido. La alerta aparece porque la actividad no cayó en la misma proporción que las obligaciones registradas. El movimiento puede ser pago real, refinanciación, reclasificación o una obligación registrada en otra cuenta.`,`Pasivo total ↔ Proveedores ↔ Acreedores ↔ Impuestos ↔ Deuda ↔ Flujo`,`El sistema debe comprobar primero si el Flujo explica la reducción del pasivo. Si la explica, NO pedir documentación. Si no la explica, pedir detalle de deuda con proveedores y referencias bancarias, y revisar posibles obligaciones fuera de Proveedores.`)
    if(res!=null&&res>0&&cash!=null&&cashP!=null&&cash<cashP){
      const drop=cashP-cash,drivers=[];if(clientDelta>0)drivers.push(`Clientes +G. ${money(clientDelta)}`);if(invDelta>0)drivers.push(`Inventario +G. ${money(invDelta)}`);if(provDelta<0)drivers.push(`Proveedores -G. ${money(Math.abs(provDelta))}`);if(debt<debtP)drivers.push(`Deuda -G. ${money(debtP-debt)}`);if(flowCash!=null&&Math.abs(flowCash-(cash-cashP))<=1)drivers.push(`Flujo de caja conciliado: G. ${money(flowCash)}`);
      add('MEDIA','Resultado positivo pero caja se debilita',`Resultado neto G. ${money(res)}; Caja/Bancos G. ${money(cashP)} → G. ${money(cash)}; disminución G. ${money(drop)}.${drivers.length?' El sistema identifica: '+drivers.join('; ')+'.':''}`,drivers.length?`La utilidad existe en el resultado, pero el efectivo fue absorbido por los movimientos indicados. Por eso una ganancia no significa automáticamente que haya más capacidad de pago disponible.`:`El resultado es positivo, pero la documentación cargada no identifica todavía qué movimiento absorbió la caja.`,`Resultado neto ↔ Clientes ↔ Inventario ↔ Proveedores ↔ Deuda ↔ Flujo ↔ Caja`,`Si los movimientos identificados explican la disminución de Caja, NO pedir documentación adicional. Si queda una diferencia material sin explicar, revisar primero el puente de efectivo y solo después solicitar información específica.`)
    }
    if(inter!=null&&Math.abs(inter)>0&&debt===0){const net=(newDebt||0)-(payDebt||0);add('ALTA','Intereses sin deuda financiera al cierre',`Intereses G. ${money(inter)} y deuda financiera al cierre G. 0.${newDebt!=null||payDebt!=null?' Flujo de deuda: nuevas G. '+money(newDebt)+'; pagos G. '+money(payDebt)+'.':''}`,`Puede ser deuda cancelada durante el año, intereses de períodos anteriores, refinanciación o una obligación registrada en otra cuenta.`,`Intereses ↔ Deuda CP/LP ↔ Nuevas deudas ↔ Pagos de deuda ↔ Flujo`,`Si nuevas deudas y pagos explican que la deuda terminó en cero, NO pedir documentación. Si no cierran, pedir detalle de deuda y referencias bancarias.`)}
    const order={ALTA:0,MEDIA:1};f.sort((a,b)=>order[a.level]-order[b.level]);return {current:cur,prev,a:f}
  }
  function grade(a){const hi=a.filter(x=>x.level==='ALTA').length,me=a.filter(x=>x.level==='MEDIA').length;if(hi>=2)return['MALO','Hay varias señales relevantes sin explicación suficiente en el período actual.','g-bad'];if(hi===1)return['REGULAR','Existe una señal relevante que debe comprobarse antes de tomar una decisión de crédito.','g-warn'];if(me>=2)return['REGULAR','Hay varias señales actuales que requieren revisión, aunque no demuestran por sí solas una inconsistencia.','g-warn'];if(me===1)return['BIEN','Existe una señal puntual, pero los estados permiten una lectura general razonable.','g-good'];return['EXCELENTE','No se detectan señales relevantes con la información disponible del período actual.','g-excellent']}
  function render(r){const a=$('auditoria');if(!a)return;document.getElementById('diagnosticoV2')?.remove();const g=grade(r.a),sec=document.createElement('section');sec.id='diagnosticoV2';sec.className='card';const alerts=r.a.slice(0,5);sec.innerHTML=`<h2>4. CONCLUSIÓN CREDITICIA — ${esc(r.current)}</h2><div class="body credit-v2"><div class="v2-grade ${g[2]}"><div class="v2-kicker">RESULTADO DEL PERÍODO ACTUAL</div><div class="v2-value">${esc(g[0])}</div><div class="v2-summary">${esc(g[1])}</div><div class="v2-rule"><b>Regla:</b> ${esc(r.current)} determina la conclusión. ${esc(r.prev)} y los períodos anteriores solo miden tendencia y deterioro.</div></div>${alerts.length?`<h3>ALERTAS QUE CAMBIAN LA LECTURA DEL CRÉDITO</h3><div class="v2-alerts">${alerts.map((x,i)=>`<article class="v2-alert level-${x.level.toLowerCase()}"><div class="v2-head"><div><span class="v2-num">${i+1}</span><b>${esc(x.title)}</b></div><span class="v2-priority">${esc(x.level)}</span></div><div class="v2-row"><b>QUÉ DETECTÓ</b><span>${esc(x.detected)}</span></div><div class="v2-row"><b>QUÉ SIGNIFICA</b><span>${esc(x.meaning)}</span></div><div class="v2-row"><b>CUENTAS QUE RELACIONÓ</b><span>${esc(x.accounts)}</span></div><div class="v2-row action"><b>DECISIÓN SOBRE DOCUMENTACIÓN</b><span>${esc(x.action)}</span></div></article>`).join('')}</div>`:`<div class="v2-clean"><b>NO HAY ALERTAS RELEVANTES EN ${esc(r.current)}.</b></div>`}<details class="v2-method"><summary>Ver cálculo técnico</summary><div>El sistema usa relaciones entre cuentas y, cuando está disponible, las contrasta con el Flujo. Una señal no acusa error: indica que el comportamiento requiere explicación. La solicitud de documentos se activa solamente cuando la información cargada no explica el movimiento.</div></details></div>`;a.appendChild(sec);[...a.children].forEach(el=>{if(el.id!=='flujoCompacto'&&el.id!=='diagnosticoV2')el.style.display='none'});}
  function init(){const b=$('leer');if(!b)return;b.addEventListener('click',()=>setTimeout(()=>read().then(d=>{if(d)render(analyze(d))}),450))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
